# Form implementation generated from reading ui file 'C:\Users\OS\LAVY\LAVY_FINALPROJECT\UI\HomePage.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1500, 900)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.widget_2 = QtWidgets.QWidget(parent=self.centralwidget)
        self.widget_2.setGeometry(QtCore.QRect(0, -1, 1500, 951))
        self.widget_2.setObjectName("widget_2")
        self.labelHomepagebackground = QtWidgets.QLabel(parent=self.widget_2)
        self.labelHomepagebackground.setGeometry(QtCore.QRect(0, -10, 1500, 911))
        self.labelHomepagebackground.setStyleSheet("")
        self.labelHomepagebackground.setText("")
        self.labelHomepagebackground.setPixmap(QtGui.QPixmap("C:\\Users\\OS\\LAVY\\LAVY_FINALPROJECT\\UI\\../Images/background.jpg"))
        self.labelHomepagebackground.setScaledContents(True)
        self.labelHomepagebackground.setObjectName("labelHomepagebackground")
        self.labelBackground = QtWidgets.QLabel(parent=self.widget_2)
        self.labelBackground.setGeometry(QtCore.QRect(-10, -60, 1511, 1200))
        self.labelBackground.setStyleSheet("background-color: rgba(0,0,0,150);\n"
"")
        self.labelBackground.setText("")
        self.labelBackground.setScaledContents(True)
        self.labelBackground.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.labelBackground.setObjectName("labelBackground")
        self.widgetTitle = QtWidgets.QWidget(parent=self.widget_2)
        self.widgetTitle.setGeometry(QtCore.QRect(330, 240, 851, 121))
        self.widgetTitle.setObjectName("widgetTitle")
        self.labelDiscover = QtWidgets.QLabel(parent=self.widgetTitle)
        self.labelDiscover.setGeometry(QtCore.QRect(60, 80, 731, 51))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(15)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        font.setStyleStrategy(QtGui.QFont.StyleStrategy.PreferDefault)
        self.labelDiscover.setFont(font)
        self.labelDiscover.setStyleSheet("COLOR: rgb(255, 255, 255)")
        self.labelDiscover.setObjectName("labelDiscover")
        self.labelWelcome = QtWidgets.QLabel(parent=self.widgetTitle)
        self.labelWelcome.setGeometry(QtCore.QRect(190, 0, 471, 91))
        font = QtGui.QFont()
        font.setFamily("VNI-Ariston")
        font.setPointSize(44)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.labelWelcome.setFont(font)
        self.labelWelcome.setStyleSheet("color: rgb(255, 255, 255);")
        self.labelWelcome.setScaledContents(False)
        self.labelWelcome.setObjectName("labelWelcome")
        self.frameMain = QtWidgets.QFrame(parent=self.widget_2)
        self.frameMain.setGeometry(QtCore.QRect(60, 480, 1411, 301))
        self.frameMain.setStyleSheet("background-color: transparent")
        self.frameMain.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frameMain.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frameMain.setObjectName("frameMain")
        self.widget4 = QtWidgets.QWidget(parent=self.frameMain)
        self.widget4.setGeometry(QtCore.QRect(840, 0, 260, 301))
        self.widget4.setStyleSheet("background-color: rgba(0,0,0,150);\n"
"")
        self.widget4.setObjectName("widget4")
        self.labelfigure4 = QtWidgets.QLabel(parent=self.widget4)
        self.labelfigure4.setGeometry(QtCore.QRect(10, 10, 241, 171))
        font = QtGui.QFont()
        font.setFamily("Sitka Text")
        font.setPointSize(10)
        self.labelfigure4.setFont(font)
        self.labelfigure4.setText("")
        self.labelfigure4.setPixmap(QtGui.QPixmap("C:\\Users\\OS\\LAVY\\LAVY_FINALPROJECT\\UI\\../Images/rest4.jpg"))
        self.labelfigure4.setScaledContents(True)
        self.labelfigure4.setObjectName("labelfigure4")
        self.verticalWidget4 = QtWidgets.QWidget(parent=self.widget4)
        self.verticalWidget4.setGeometry(QtCore.QRect(0, 190, 261, 111))
        self.verticalWidget4.setObjectName("verticalWidget4")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.verticalWidget4)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.pushButtonName4 = QtWidgets.QPushButton(parent=self.verticalWidget4)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonName4.setFont(font)
        self.pushButtonName4.setStyleSheet("color:rgb(255, 255, 255)")
        self.pushButtonName4.setObjectName("pushButtonName4")
        self.verticalLayout_6.addWidget(self.pushButtonName4)
        self.labelrating4 = QtWidgets.QLabel(parent=self.verticalWidget4)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        self.labelrating4.setFont(font)
        self.labelrating4.setStyleSheet("color:rgb(255, 255, 255)")
        self.labelrating4.setScaledContents(False)
        self.labelrating4.setWordWrap(True)
        self.labelrating4.setObjectName("labelrating4")
        self.verticalLayout_6.addWidget(self.labelrating4)
        self.widget5 = QtWidgets.QWidget(parent=self.frameMain)
        self.widget5.setGeometry(QtCore.QRect(1120, 0, 260, 301))
        self.widget5.setStyleSheet("background-color: rgba(0,0,0,150);\n"
"")
        self.widget5.setObjectName("widget5")
        self.labelfigure5 = QtWidgets.QLabel(parent=self.widget5)
        self.labelfigure5.setGeometry(QtCore.QRect(10, 10, 241, 171))
        font = QtGui.QFont()
        font.setFamily("Sitka Text")
        font.setPointSize(10)
        self.labelfigure5.setFont(font)
        self.labelfigure5.setText("")
        self.labelfigure5.setPixmap(QtGui.QPixmap("C:\\Users\\OS\\LAVY\\LAVY_FINALPROJECT\\UI\\../Images/rest5.jpg"))
        self.labelfigure5.setScaledContents(True)
        self.labelfigure5.setObjectName("labelfigure5")
        self.verticalWidget5 = QtWidgets.QWidget(parent=self.widget5)
        self.verticalWidget5.setGeometry(QtCore.QRect(0, 190, 261, 111))
        self.verticalWidget5.setObjectName("verticalWidget5")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.verticalWidget5)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.pushButtonName5 = QtWidgets.QPushButton(parent=self.verticalWidget5)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonName5.setFont(font)
        self.pushButtonName5.setStyleSheet("color:rgb(255, 255, 255)")
        self.pushButtonName5.setObjectName("pushButtonName5")
        self.verticalLayout_8.addWidget(self.pushButtonName5)
        self.labelrating5 = QtWidgets.QLabel(parent=self.verticalWidget5)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        self.labelrating5.setFont(font)
        self.labelrating5.setStyleSheet("color:rgb(255, 255, 255)")
        self.labelrating5.setScaledContents(False)
        self.labelrating5.setWordWrap(True)
        self.labelrating5.setObjectName("labelrating5")
        self.verticalLayout_8.addWidget(self.labelrating5)
        self.widget3 = QtWidgets.QWidget(parent=self.frameMain)
        self.widget3.setGeometry(QtCore.QRect(560, 0, 260, 301))
        self.widget3.setStyleSheet("background-color: rgba(0,0,0,150);\n"
"")
        self.widget3.setObjectName("widget3")
        self.labelfigure3 = QtWidgets.QLabel(parent=self.widget3)
        self.labelfigure3.setGeometry(QtCore.QRect(10, 10, 241, 171))
        font = QtGui.QFont()
        font.setFamily("Sitka Text")
        font.setPointSize(10)
        self.labelfigure3.setFont(font)
        self.labelfigure3.setText("")
        self.labelfigure3.setPixmap(QtGui.QPixmap("C:\\Users\\OS\\LAVY\\LAVY_FINALPROJECT\\UI\\../Images/rest3.jpg"))
        self.labelfigure3.setScaledContents(True)
        self.labelfigure3.setObjectName("labelfigure3")
        self.verticalWidget3 = QtWidgets.QWidget(parent=self.widget3)
        self.verticalWidget3.setGeometry(QtCore.QRect(0, 190, 261, 111))
        self.verticalWidget3.setObjectName("verticalWidget3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalWidget3)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.pushButtonName3 = QtWidgets.QPushButton(parent=self.verticalWidget3)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonName3.setFont(font)
        self.pushButtonName3.setStyleSheet("color:rgb(255, 255, 255)")
        self.pushButtonName3.setObjectName("pushButtonName3")
        self.verticalLayout_3.addWidget(self.pushButtonName3)
        self.labelrating3 = QtWidgets.QLabel(parent=self.verticalWidget3)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        self.labelrating3.setFont(font)
        self.labelrating3.setStyleSheet("color:rgb(255, 255, 255)")
        self.labelrating3.setScaledContents(False)
        self.labelrating3.setWordWrap(True)
        self.labelrating3.setObjectName("labelrating3")
        self.verticalLayout_3.addWidget(self.labelrating3)
        self.widget1 = QtWidgets.QWidget(parent=self.frameMain)
        self.widget1.setGeometry(QtCore.QRect(0, 0, 260, 301))
        self.widget1.setStyleSheet("background-color: rgba(0,0,0,150);\n"
"")
        self.widget1.setObjectName("widget1")
        self.labelfigure1 = QtWidgets.QLabel(parent=self.widget1)
        self.labelfigure1.setGeometry(QtCore.QRect(10, 10, 241, 171))
        font = QtGui.QFont()
        font.setFamily("Sitka Text")
        font.setPointSize(10)
        self.labelfigure1.setFont(font)
        self.labelfigure1.setStyleSheet("border-radius: 20px;")
        self.labelfigure1.setText("")
        self.labelfigure1.setPixmap(QtGui.QPixmap("C:\\Users\\OS\\LAVY\\LAVY_FINALPROJECT\\UI\\../Images/rest1.jpg"))
        self.labelfigure1.setScaledContents(True)
        self.labelfigure1.setObjectName("labelfigure1")
        self.verticalWidget1 = QtWidgets.QWidget(parent=self.widget1)
        self.verticalWidget1.setGeometry(QtCore.QRect(0, 190, 261, 111))
        self.verticalWidget1.setObjectName("verticalWidget1")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.verticalWidget1)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.pushButtonName1 = QtWidgets.QPushButton(parent=self.verticalWidget1)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonName1.setFont(font)
        self.pushButtonName1.setStyleSheet("color:rgb(255, 255, 255)")
        self.pushButtonName1.setObjectName("pushButtonName1")
        self.verticalLayout_4.addWidget(self.pushButtonName1)
        self.labelrating1 = QtWidgets.QLabel(parent=self.verticalWidget1)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        self.labelrating1.setFont(font)
        self.labelrating1.setStyleSheet("color:rgb(255, 255, 255)")
        self.labelrating1.setScaledContents(False)
        self.labelrating1.setWordWrap(True)
        self.labelrating1.setObjectName("labelrating1")
        self.verticalLayout_4.addWidget(self.labelrating1)
        self.widget2 = QtWidgets.QWidget(parent=self.frameMain)
        self.widget2.setGeometry(QtCore.QRect(280, 0, 260, 301))
        self.widget2.setStyleSheet("background-color: rgba(0,0,0,150);\n"
"")
        self.widget2.setObjectName("widget2")
        self.labelfigure2 = QtWidgets.QLabel(parent=self.widget2)
        self.labelfigure2.setGeometry(QtCore.QRect(10, 10, 241, 171))
        font = QtGui.QFont()
        font.setFamily("Sitka Text")
        font.setPointSize(10)
        self.labelfigure2.setFont(font)
        self.labelfigure2.setText("")
        self.labelfigure2.setPixmap(QtGui.QPixmap("C:\\Users\\OS\\LAVY\\LAVY_FINALPROJECT\\UI\\../Images/rest2.jpg"))
        self.labelfigure2.setScaledContents(True)
        self.labelfigure2.setObjectName("labelfigure2")
        self.verticalWidget2 = QtWidgets.QWidget(parent=self.widget2)
        self.verticalWidget2.setGeometry(QtCore.QRect(0, 190, 261, 111))
        self.verticalWidget2.setObjectName("verticalWidget2")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.verticalWidget2)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.pushButtonName2 = QtWidgets.QPushButton(parent=self.verticalWidget2)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonName2.setFont(font)
        self.pushButtonName2.setStyleSheet("color:rgb(255, 255, 255)")
        self.pushButtonName2.setObjectName("pushButtonName2")
        self.verticalLayout_5.addWidget(self.pushButtonName2)
        self.labelrating2 = QtWidgets.QLabel(parent=self.verticalWidget2)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        self.labelrating2.setFont(font)
        self.labelrating2.setStyleSheet("color:rgb(255, 255, 255)")
        self.labelrating2.setScaledContents(False)
        self.labelrating2.setWordWrap(True)
        self.labelrating2.setObjectName("labelrating2")
        self.verticalLayout_5.addWidget(self.labelrating2)
        self.TitleBar = QtWidgets.QWidget(parent=self.widget_2)
        self.TitleBar.setGeometry(QtCore.QRect(0, 0, 1500, 101))
        self.TitleBar.setStyleSheet("background-color: rgba(0,0,0,150);\n"
"")
        self.TitleBar.setObjectName("TitleBar")
        self.lineEditSearch = QtWidgets.QLineEdit(parent=self.TitleBar)
        self.lineEditSearch.setGeometry(QtCore.QRect(350, 20, 601, 61))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lineEditSearch.setFont(font)
        self.lineEditSearch.setStyleSheet("COLOR: rgb(255, 255, 255);\n"
"background-color: rgba(0,0,0,180);\n"
"\n"
"border-radius: 30px;\n"
"padding-left: 20px;\n"
"")
        self.lineEditSearch.setText("")
        self.lineEditSearch.setObjectName("lineEditSearch")
        self.pushButtonSearch = QtWidgets.QPushButton(parent=self.TitleBar)
        self.pushButtonSearch.setGeometry(QtCore.QRect(880, 30, 41, 41))
        self.pushButtonSearch.setStyleSheet("QPushButton {\n"
"    background-color: transparent;\n"
"    border-radius: 10px;\n"
"    padding: 5px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgb(71, 71, 71); \n"
"};\n"
"\n"
"")
        self.pushButtonSearch.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("C:\\Users\\OS\\LAVY\\LAVY_FINALPROJECT\\UI\\../Images/ic_search.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButtonSearch.setIcon(icon)
        self.pushButtonSearch.setIconSize(QtCore.QSize(50, 50))
        self.pushButtonSearch.setObjectName("pushButtonSearch")
        self.pushButtonWriteReview = QtWidgets.QPushButton(parent=self.TitleBar)
        self.pushButtonWriteReview.setGeometry(QtCore.QRect(960, 20, 221, 60))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonWriteReview.setFont(font)
        self.pushButtonWriteReview.setStyleSheet("QPushButton {\n"
"    background-color: transparent;\n"
"    border-radius: 10px;\n"
"    padding: 5px;\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgb(71, 71, 71); \n"
"};\n"
"\n"
"")
        self.pushButtonWriteReview.setObjectName("pushButtonWriteReview")
        self.pushButtonLogIn = QtWidgets.QPushButton(parent=self.TitleBar)
        self.pushButtonLogIn.setGeometry(QtCore.QRect(1200, 20, 140, 60))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.pushButtonLogIn.setFont(font)
        self.pushButtonLogIn.setStyleSheet("\n"
"QPushButton {\n"
"    background-color: rgb(255, 255, 255);\n"
"    border-radius: 10px;\n"
"    padding: 5px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgba(231, 230, 230, 252); \n"
"    color: black;\n"
"};\n"
"\n"
"")
        self.pushButtonLogIn.setObjectName("pushButtonLogIn")
        self.labelValy = QtWidgets.QLabel(parent=self.TitleBar)
        self.labelValy.setGeometry(QtCore.QRect(150, 0, 180, 101))
        font = QtGui.QFont()
        font.setFamily("VNI-Ariston")
        font.setPointSize(28)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.labelValy.setFont(font)
        self.labelValy.setStyleSheet("background-color: transparent;\n"
"color: rgb(255, 255, 255);\n"
"\n"
"font: 75 28pt \"VNI-Ariston\";")
        self.labelValy.setScaledContents(True)
        self.labelValy.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.labelValy.setObjectName("labelValy")
        self.pushButtonSignUp = QtWidgets.QPushButton(parent=self.TitleBar)
        self.pushButtonSignUp.setGeometry(QtCore.QRect(1350, 20, 140, 60))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.pushButtonSignUp.setFont(font)
        self.pushButtonSignUp.setStyleSheet("\n"
"QPushButton {\n"
"    background-color: rgb(255, 255, 255);\n"
"    border-radius: 10px;\n"
"    padding: 5px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgba(231, 230, 230, 252); \n"
"    color: black;\n"
"};\n"
"\n"
"")
        self.pushButtonSignUp.setObjectName("pushButtonSignUp")
        self.pushButtonWritePrevious = QtWidgets.QPushButton(parent=self.TitleBar)
        self.pushButtonWritePrevious.setGeometry(QtCore.QRect(20, 25, 51, 51))
        font = QtGui.QFont()
        font.setFamily("VNI-Souvir")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonWritePrevious.setFont(font)
        self.pushButtonWritePrevious.setStyleSheet("\n"
"\n"
"QPushButton {\n"
"    background-color: transparent;\n"
"    border-radius: 10px;\n"
"    padding: 5px;\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgb(71, 71, 71); \n"
"};\n"
"background-color: transparent;")
        self.pushButtonWritePrevious.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("C:\\Users\\OS\\LAVY\\LAVY_FINALPROJECT\\UI\\../Images/ic_left.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButtonWritePrevious.setIcon(icon1)
        self.pushButtonWritePrevious.setIconSize(QtCore.QSize(40, 40))
        self.pushButtonWritePrevious.setObjectName("pushButtonWritePrevious")
        self.pushButtonWriteNext = QtWidgets.QPushButton(parent=self.TitleBar)
        self.pushButtonWriteNext.setGeometry(QtCore.QRect(80, 25, 51, 51))
        font = QtGui.QFont()
        font.setFamily("VNI-Souvir")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonWriteNext.setFont(font)
        self.pushButtonWriteNext.setStyleSheet("\n"
"QPushButton {\n"
"    background-color: transparent;\n"
"    border-radius: 10px;\n"
"    padding: 5px;\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgb(71, 71, 71); \n"
"};\n"
"background-color: transparent;\n"
"")
        self.pushButtonWriteNext.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("C:\\Users\\OS\\LAVY\\LAVY_FINALPROJECT\\UI\\../Images/ic_right.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButtonWriteNext.setIcon(icon2)
        self.pushButtonWriteNext.setIconSize(QtCore.QSize(40, 40))
        self.pushButtonWriteNext.setObjectName("pushButtonWriteNext")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.labelDiscover.setText(_translate("MainWindow", "Discover the best restaurants near you and enjoy an amazing dining experience!"))
        self.labelWelcome.setText(_translate("MainWindow", "Welcome to Valy"))
        self.pushButtonName4.setText(_translate("MainWindow", "Shanghai Teahouse"))
        self.labelrating4.setText(_translate("MainWindow", "Sit-in to savour a delicious cocktail with your meal, or enjoy a selection of our favourites to take away"))
        self.pushButtonName5.setText(_translate("MainWindow", "Chon Thai"))
        self.labelrating5.setText(_translate("MainWindow", "Thai cuisine is the delicious paradox of contrast and harmony, requiring the deft, experienced touch of a master chef."))
        self.pushButtonName3.setText(_translate("MainWindow", "Hakushu"))
        self.labelrating3.setText(_translate("MainWindow", "Hakushu Kobe Teppanyaki for more than 50 yrs in Shibuya. TripAdvisor Traveler\'s Choice Award 2016-2019"))
        self.pushButtonName1.setText(_translate("MainWindow", "Le Train Bleu Paris"))
        self.labelrating1.setText(_translate("MainWindow", "Listed historical monument inside the station at the first floor, the restaurant \"Le Train Bleu\" is opened every day for lunch and dinner."))
        self.pushButtonName2.setText(_translate("MainWindow", "Manhatta"))
        self.labelrating2.setText(_translate("MainWindow", "Manhatta is a love letter to New York City. Perched sixty floors up, embodying the spirit of a tried-and-true New Yorker, "))
        self.lineEditSearch.setWhatsThis(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.lineEditSearch.setPlaceholderText(_translate("MainWindow", "Search for the restaurant..."))
        self.pushButtonWriteReview.setText(_translate("MainWindow", "Write a review"))
        self.pushButtonLogIn.setText(_translate("MainWindow", "Log In"))
        self.labelValy.setText(_translate("MainWindow", "Valy"))
        self.pushButtonSignUp.setText(_translate("MainWindow", "Sign Up"))
