# Form implementation generated from reading ui file 'C:\Users\OS\LAVY\LAVY_FINALPROJECT\UI\HomePageAfterRating.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_HomePageAfterRating(object):
    def setupUi(self, HomePageAfterRating):
        HomePageAfterRating.setObjectName("HomePageAfterRating")
        HomePageAfterRating.resize(1501, 900)
        self.centralwidget = QtWidgets.QWidget(parent=HomePageAfterRating)
        self.centralwidget.setObjectName("centralwidget")
        self.TitleBar = QtWidgets.QWidget(parent=self.centralwidget)
        self.TitleBar.setGeometry(QtCore.QRect(0, 0, 1500, 101))
        self.TitleBar.setStyleSheet("background-color: rgba(0,0,0,150);\n"
"")
        self.TitleBar.setObjectName("TitleBar")
        self.lineEditSearch = QtWidgets.QLineEdit(parent=self.TitleBar)
        self.lineEditSearch.setGeometry(QtCore.QRect(350, 20, 601, 61))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lineEditSearch.setFont(font)
        self.lineEditSearch.setStyleSheet("COLOR: rgb(255, 255, 255);\n"
"background-color: rgba(0,0,0,180);\n"
"\n"
"border-radius: 30px;\n"
"padding-left: 20px;\n"
"")
        self.lineEditSearch.setText("")
        self.lineEditSearch.setObjectName("lineEditSearch")
        self.pushButtonSearch = QtWidgets.QPushButton(parent=self.TitleBar)
        self.pushButtonSearch.setGeometry(QtCore.QRect(880, 30, 41, 41))
        self.pushButtonSearch.setStyleSheet("QPushButton {\n"
"    background-color: transparent;\n"
"    border-radius: 10px;\n"
"    padding: 5px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgb(71, 71, 71); \n"
"};\n"
"\n"
"")
        self.pushButtonSearch.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("C:\\Users\\OS\\LAVY\\LAVY_FINALPROJECT\\UI\\../Images/ic_search.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButtonSearch.setIcon(icon)
        self.pushButtonSearch.setIconSize(QtCore.QSize(50, 50))
        self.pushButtonSearch.setObjectName("pushButtonSearch")
        self.pushButtonWriteReview = QtWidgets.QPushButton(parent=self.TitleBar)
        self.pushButtonWriteReview.setGeometry(QtCore.QRect(1110, 20, 221, 60))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonWriteReview.setFont(font)
        self.pushButtonWriteReview.setStyleSheet("QPushButton {\n"
"    background-color: transparent;\n"
"    border-radius: 10px;\n"
"    padding: 5px;\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgb(71, 71, 71); \n"
"};\n"
"\n"
"")
        self.pushButtonWriteReview.setObjectName("pushButtonWriteReview")
        self.pushButtonLogOut = QtWidgets.QPushButton(parent=self.TitleBar)
        self.pushButtonLogOut.setGeometry(QtCore.QRect(1350, 20, 140, 60))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.pushButtonLogOut.setFont(font)
        self.pushButtonLogOut.setStyleSheet("\n"
"QPushButton {\n"
"    background-color: rgb(255, 255, 255);\n"
"    border-radius: 10px;\n"
"    padding: 5px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgba(231, 230, 230, 252); \n"
"    color: black;\n"
"};\n"
"\n"
"")
        self.pushButtonLogOut.setObjectName("pushButtonLogOut")
        self.pushButtonWritePrevious = QtWidgets.QPushButton(parent=self.TitleBar)
        self.pushButtonWritePrevious.setGeometry(QtCore.QRect(20, 25, 51, 51))
        font = QtGui.QFont()
        font.setFamily("VNI-Souvir")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonWritePrevious.setFont(font)
        self.pushButtonWritePrevious.setStyleSheet("\n"
"\n"
"QPushButton {\n"
"    background-color: transparent;\n"
"    border-radius: 10px;\n"
"    padding: 5px;\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgb(71, 71, 71); \n"
"};\n"
"background-color: transparent;")
        self.pushButtonWritePrevious.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("C:\\Users\\OS\\LAVY\\LAVY_FINALPROJECT\\UI\\../Images/ic_left.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButtonWritePrevious.setIcon(icon1)
        self.pushButtonWritePrevious.setIconSize(QtCore.QSize(40, 40))
        self.pushButtonWritePrevious.setObjectName("pushButtonWritePrevious")
        self.pushButtonWriteNext = QtWidgets.QPushButton(parent=self.TitleBar)
        self.pushButtonWriteNext.setGeometry(QtCore.QRect(80, 25, 51, 51))
        font = QtGui.QFont()
        font.setFamily("VNI-Souvir")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonWriteNext.setFont(font)
        self.pushButtonWriteNext.setStyleSheet("\n"
"QPushButton {\n"
"    background-color: transparent;\n"
"    border-radius: 10px;\n"
"    padding: 5px;\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgb(71, 71, 71); \n"
"};\n"
"background-color: transparent;\n"
"")
        self.pushButtonWriteNext.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("C:\\Users\\OS\\LAVY\\LAVY_FINALPROJECT\\UI\\../Images/ic_right.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButtonWriteNext.setIcon(icon2)
        self.pushButtonWriteNext.setIconSize(QtCore.QSize(40, 40))
        self.pushButtonWriteNext.setObjectName("pushButtonWriteNext")
        self.labelValy = QtWidgets.QLabel(parent=self.TitleBar)
        self.labelValy.setGeometry(QtCore.QRect(150, 0, 180, 101))
        font = QtGui.QFont()
        font.setFamily("VNI-Ariston")
        font.setPointSize(28)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.labelValy.setFont(font)
        self.labelValy.setStyleSheet("background-color: transparent;\n"
"color: rgb(255, 255, 255);\n"
"font: 75 28pt \"VNI-Ariston\";")
        self.labelValy.setScaledContents(True)
        self.labelValy.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.labelValy.setObjectName("labelValy")
        self.widgetBGMain = QtWidgets.QWidget(parent=self.centralwidget)
        self.widgetBGMain.setGeometry(QtCore.QRect(-10, 90, 1511, 811))
        self.widgetBGMain.setStyleSheet("background-color: RGBA(0,0,0,100)")
        self.widgetBGMain.setObjectName("widgetBGMain")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.widgetBGMain)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.scrollArea = QtWidgets.QScrollArea(parent=self.widgetBGMain)
        self.scrollArea.setStyleSheet("background-color: transparent;\n"
"border:none")
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, -479, 1476, 3250))
        self.scrollAreaWidgetContents.setMinimumSize(QtCore.QSize(0, 3250))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.frameMain = QtWidgets.QFrame(parent=self.scrollAreaWidgetContents)
        self.frameMain.setMinimumSize(QtCore.QSize(0, 0))
        self.frameMain.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frameMain.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frameMain.setObjectName("frameMain")
        self.widget = QtWidgets.QWidget(parent=self.frameMain)
        self.widget.setGeometry(QtCore.QRect(-10, -20, 1591, 3261))
        self.widget.setStyleSheet("background-color: transparent")
        self.widget.setObjectName("widget")
        self.frameResult = QtWidgets.QFrame(parent=self.widget)
        self.frameResult.setGeometry(QtCore.QRect(180, 180, 1111, 2971))
        self.frameResult.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frameResult.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frameResult.setObjectName("frameResult")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.frameResult)
        self.verticalLayout_6.setSpacing(15)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.frameResult1 = QtWidgets.QFrame(parent=self.frameResult)
        self.frameResult1.setStyleSheet("QFrame {\n"
"    background-color: rgba(0, 0, 0, 200);\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"QFrame:hover {\n"
"    background-color: rgba(0,0,0,100);\n"
"}\n"
"")
        self.frameResult1.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frameResult1.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frameResult1.setObjectName("frameResult1")
        self.labelRate1 = QtWidgets.QLabel(parent=self.frameResult1)
        self.labelRate1.setGeometry(QtCore.QRect(330, 220, 211, 51))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.labelRate1.setFont(font)
        self.labelRate1.setStyleSheet("background-color: transparent;\n"
"font: 75 14pt \"Georgia\";\n"
"COLOR: rgb(255, 255, 255);")
        self.labelRate1.setText("")
        self.labelRate1.setObjectName("labelRate1")
        self.labelFigure1 = QtWidgets.QLabel(parent=self.frameResult1)
        self.labelFigure1.setGeometry(QtCore.QRect(10, 15, 250, 251))
        font = QtGui.QFont()
        font.setFamily("Sitka Text")
        font.setPointSize(10)
        self.labelFigure1.setFont(font)
        self.labelFigure1.setStyleSheet("background-color: transparent;\n"
"border-radius: 10px;")
        self.labelFigure1.setText("")
        self.labelFigure1.setObjectName("labelFigure1")
        self.labelLocation1 = QtWidgets.QLabel(parent=self.frameResult1)
        self.labelLocation1.setGeometry(QtCore.QRect(330, 80, 751, 51))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.labelLocation1.setFont(font)
        self.labelLocation1.setStyleSheet("background-color: transparent;\n"
"font: 75 14pt \"Georgia\";\n"
"COLOR: rgb(255, 255, 255);")
        self.labelLocation1.setText("")
        self.labelLocation1.setObjectName("labelLocation1")
        self.labelCategories1 = QtWidgets.QLabel(parent=self.frameResult1)
        self.labelCategories1.setGeometry(QtCore.QRect(330, 150, 751, 51))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.labelCategories1.setFont(font)
        self.labelCategories1.setStyleSheet("background-color: transparent;\n"
"font: 75 14pt \"Georgia\";\n"
"COLOR: rgb(255, 255, 255);")
        self.labelCategories1.setText("")
        self.labelCategories1.setObjectName("labelCategories1")
        self.labelRateIcon1 = QtWidgets.QLabel(parent=self.frameResult1)
        self.labelRateIcon1.setGeometry(QtCore.QRect(280, 225, 41, 41))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(30)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.labelRateIcon1.setFont(font)
        self.labelRateIcon1.setStyleSheet("font: 30pt \"MS Shell Dlg 2\";\n"
"COLOR:rgb(255, 255, 255); background-color: transparent")
        self.labelRateIcon1.setScaledContents(True)
        self.labelRateIcon1.setObjectName("labelRateIcon1")
        self.labelMessage1 = QtWidgets.QLabel(parent=self.frameResult1)
        self.labelMessage1.setGeometry(QtCore.QRect(280, 160, 41, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(23)
        self.labelMessage1.setFont(font)
        self.labelMessage1.setStyleSheet("background-color: transparent;\n"
"COLOR: rgb(255, 255, 255)")
        self.labelMessage1.setScaledContents(True)
        self.labelMessage1.setObjectName("labelMessage1")
        self.labelLocationIcon1 = QtWidgets.QLabel(parent=self.frameResult1)
        self.labelLocationIcon1.setGeometry(QtCore.QRect(280, 90, 41, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(23)
        self.labelLocationIcon1.setFont(font)
        self.labelLocationIcon1.setStyleSheet("background-color: transparent;\n"
"COLOR: rgb(255, 255, 255);")
        self.labelLocationIcon1.setScaledContents(True)
        self.labelLocationIcon1.setObjectName("labelLocationIcon1")
        self.labelName1 = QtWidgets.QLabel(parent=self.frameResult1)
        self.labelName1.setGeometry(QtCore.QRect(330, 10, 751, 61))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.labelName1.setFont(font)
        self.labelName1.setStyleSheet("background-color: transparent;\n"
"font: 75 18pt \"Georgia\";\n"
"COLOR: rgb(255, 255, 255);")
        self.labelName1.setText("")
        self.labelName1.setObjectName("labelName1")
        self.pushButtonRating1 = QtWidgets.QPushButton(parent=self.frameResult1)
        self.pushButtonRating1.setGeometry(QtCore.QRect(890, 220, 181, 51))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.pushButtonRating1.setFont(font)
        self.pushButtonRating1.setStyleSheet("\n"
"QPushButton {\n"
"    background-color: rgb(255, 255, 255);\n"
"    border-radius: 10px;\n"
"    padding: 5px;\n"
"    font: 75 18pt \"Georgia\";\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgba(231, 230, 230, 252); \n"
"    color: black;\n"
"};\n"
"\n"
"")
        self.pushButtonRating1.setObjectName("pushButtonRating1")
        self.verticalLayout_6.addWidget(self.frameResult1)
        self.frameResult2 = QtWidgets.QFrame(parent=self.frameResult)
        self.frameResult2.setStyleSheet("QFrame {\n"
"    background-color: rgba(0, 0, 0, 200);\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"QFrame:hover {\n"
"    background-color: rgba(0,0,0,150);\n"
"}\n"
"")
        self.frameResult2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frameResult2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frameResult2.setObjectName("frameResult2")
        self.labelRate2 = QtWidgets.QLabel(parent=self.frameResult2)
        self.labelRate2.setGeometry(QtCore.QRect(330, 220, 211, 51))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.labelRate2.setFont(font)
        self.labelRate2.setStyleSheet("background-color: transparent;\n"
"font: 75 14pt \"Georgia\";\n"
"COLOR: rgb(255, 255, 255);")
        self.labelRate2.setText("")
        self.labelRate2.setObjectName("labelRate2")
        self.labelFigure2 = QtWidgets.QLabel(parent=self.frameResult2)
        self.labelFigure2.setGeometry(QtCore.QRect(10, 15, 250, 251))
        font = QtGui.QFont()
        font.setFamily("Sitka Text")
        font.setPointSize(10)
        self.labelFigure2.setFont(font)
        self.labelFigure2.setStyleSheet("background-color: transparent;\n"
"border-radius: 10px;")
        self.labelFigure2.setText("")
        self.labelFigure2.setObjectName("labelFigure2")
        self.labelLocation2 = QtWidgets.QLabel(parent=self.frameResult2)
        self.labelLocation2.setGeometry(QtCore.QRect(330, 80, 751, 51))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.labelLocation2.setFont(font)
        self.labelLocation2.setStyleSheet("background-color: transparent;\n"
"font: 75 14pt \"Georgia\";\n"
"COLOR: rgb(255, 255, 255);")
        self.labelLocation2.setText("")
        self.labelLocation2.setObjectName("labelLocation2")
        self.labelCategories2 = QtWidgets.QLabel(parent=self.frameResult2)
        self.labelCategories2.setGeometry(QtCore.QRect(330, 150, 751, 51))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.labelCategories2.setFont(font)
        self.labelCategories2.setStyleSheet("background-color: transparent;\n"
"font: 75 14pt \"Georgia\";\n"
"COLOR: rgb(255, 255, 255);")
        self.labelCategories2.setText("")
        self.labelCategories2.setObjectName("labelCategories2")
        self.labelRateIcon2 = QtWidgets.QLabel(parent=self.frameResult2)
        self.labelRateIcon2.setGeometry(QtCore.QRect(280, 225, 41, 41))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(30)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.labelRateIcon2.setFont(font)
        self.labelRateIcon2.setStyleSheet("font: 30pt \"MS Shell Dlg 2\";\n"
"COLOR:rgb(255, 255, 255); background-color: transparent")
        self.labelRateIcon2.setScaledContents(True)
        self.labelRateIcon2.setObjectName("labelRateIcon2")
        self.labelMessage2 = QtWidgets.QLabel(parent=self.frameResult2)
        self.labelMessage2.setGeometry(QtCore.QRect(280, 160, 41, 41))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(23)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.labelMessage2.setFont(font)
        self.labelMessage2.setStyleSheet("font: 23pt \"MS Shell Dlg 2\";\n"
"COLOR:rgb(255, 255, 255); background-color: transparent")
        self.labelMessage2.setScaledContents(True)
        self.labelMessage2.setObjectName("labelMessage2")
        self.labelLocationIcon2 = QtWidgets.QLabel(parent=self.frameResult2)
        self.labelLocationIcon2.setGeometry(QtCore.QRect(280, 90, 41, 41))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(23)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.labelLocationIcon2.setFont(font)
        self.labelLocationIcon2.setStyleSheet("font: 23pt \"MS Shell Dlg 2\";\n"
"COLOR:rgb(255, 255, 255); background-color: transparent")
        self.labelLocationIcon2.setScaledContents(True)
        self.labelLocationIcon2.setObjectName("labelLocationIcon2")
        self.labelName2 = QtWidgets.QLabel(parent=self.frameResult2)
        self.labelName2.setGeometry(QtCore.QRect(280, 10, 801, 61))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.labelName2.setFont(font)
        self.labelName2.setStyleSheet("background-color: transparent;\n"
"font: 75 18pt \"Georgia\";\n"
"COLOR: rgb(255, 255, 255);")
        self.labelName2.setText("")
        self.labelName2.setObjectName("labelName2")
        self.pushButtonRating2 = QtWidgets.QPushButton(parent=self.frameResult2)
        self.pushButtonRating2.setGeometry(QtCore.QRect(890, 220, 181, 51))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.pushButtonRating2.setFont(font)
        self.pushButtonRating2.setStyleSheet("\n"
"QPushButton {\n"
"    background-color: rgb(255, 255, 255);\n"
"    border-radius: 10px;\n"
"    padding: 5px;\n"
"    font: 75 18pt \"Georgia\";\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgba(231, 230, 230, 252); \n"
"    color: black;\n"
"};\n"
"\n"
"")
        self.pushButtonRating2.setObjectName("pushButtonRating2")
        self.verticalLayout_6.addWidget(self.frameResult2)
        self.frameResult3 = QtWidgets.QFrame(parent=self.frameResult)
        self.frameResult3.setStyleSheet("QFrame {\n"
"    background-color: rgba(0, 0, 0, 200);\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"QFrame:hover {\n"
"    background-color: rgba(0,0,0,150);\n"
"}\n"
"")
        self.frameResult3.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frameResult3.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frameResult3.setObjectName("frameResult3")
        self.labelRate3 = QtWidgets.QLabel(parent=self.frameResult3)
        self.labelRate3.setGeometry(QtCore.QRect(330, 220, 211, 51))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.labelRate3.setFont(font)
        self.labelRate3.setStyleSheet("background-color: transparent;\n"
"font: 75 14pt \"Georgia\";\n"
"COLOR: rgb(255, 255, 255);")
        self.labelRate3.setText("")
        self.labelRate3.setObjectName("labelRate3")
        self.labelFigure3 = QtWidgets.QLabel(parent=self.frameResult3)
        self.labelFigure3.setGeometry(QtCore.QRect(10, 15, 250, 251))
        font = QtGui.QFont()
        font.setFamily("Sitka Text")
        font.setPointSize(10)
        self.labelFigure3.setFont(font)
        self.labelFigure3.setStyleSheet("background-color: transparent;\n"
"border-radius: 10px;")
        self.labelFigure3.setText("")
        self.labelFigure3.setObjectName("labelFigure3")
        self.labelLocation3 = QtWidgets.QLabel(parent=self.frameResult3)
        self.labelLocation3.setGeometry(QtCore.QRect(330, 80, 751, 51))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.labelLocation3.setFont(font)
        self.labelLocation3.setStyleSheet("background-color: transparent;\n"
"font: 75 14pt \"Georgia\";\n"
"COLOR: rgb(255, 255, 255);")
        self.labelLocation3.setText("")
        self.labelLocation3.setObjectName("labelLocation3")
        self.labelCategories3 = QtWidgets.QLabel(parent=self.frameResult3)
        self.labelCategories3.setGeometry(QtCore.QRect(330, 150, 751, 51))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.labelCategories3.setFont(font)
        self.labelCategories3.setStyleSheet("background-color: transparent;\n"
"font: 75 14pt \"Georgia\";\n"
"COLOR: rgb(255, 255, 255);")
        self.labelCategories3.setText("")
        self.labelCategories3.setObjectName("labelCategories3")
        self.labelRateIcon3 = QtWidgets.QLabel(parent=self.frameResult3)
        self.labelRateIcon3.setGeometry(QtCore.QRect(280, 225, 41, 41))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(30)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.labelRateIcon3.setFont(font)
        self.labelRateIcon3.setStyleSheet("font: 30pt \"MS Shell Dlg 2\";\n"
"COLOR:rgb(255, 255, 255); background-color: transparent")
        self.labelRateIcon3.setScaledContents(True)
        self.labelRateIcon3.setObjectName("labelRateIcon3")
        self.labelMessage3 = QtWidgets.QLabel(parent=self.frameResult3)
        self.labelMessage3.setGeometry(QtCore.QRect(280, 160, 41, 41))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(23)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.labelMessage3.setFont(font)
        self.labelMessage3.setStyleSheet("font: 23pt \"MS Shell Dlg 2\";\n"
"COLOR:rgb(255, 255, 255); background-color: transparent")
        self.labelMessage3.setScaledContents(True)
        self.labelMessage3.setObjectName("labelMessage3")
        self.labelLocationIcon3 = QtWidgets.QLabel(parent=self.frameResult3)
        self.labelLocationIcon3.setGeometry(QtCore.QRect(280, 90, 41, 41))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(23)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.labelLocationIcon3.setFont(font)
        self.labelLocationIcon3.setStyleSheet("font: 23pt \"MS Shell Dlg 2\";\n"
"COLOR:rgb(255, 255, 255); background-color: transparent")
        self.labelLocationIcon3.setScaledContents(True)
        self.labelLocationIcon3.setObjectName("labelLocationIcon3")
        self.labelName3 = QtWidgets.QLabel(parent=self.frameResult3)
        self.labelName3.setGeometry(QtCore.QRect(280, 10, 801, 61))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.labelName3.setFont(font)
        self.labelName3.setStyleSheet("background-color: transparent;\n"
"font: 75 18pt \"Georgia\";\n"
"COLOR: rgb(255, 255, 255);")
        self.labelName3.setText("")
        self.labelName3.setObjectName("labelName3")
        self.pushButtonRating3 = QtWidgets.QPushButton(parent=self.frameResult3)
        self.pushButtonRating3.setGeometry(QtCore.QRect(890, 220, 181, 51))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.pushButtonRating3.setFont(font)
        self.pushButtonRating3.setStyleSheet("\n"
"QPushButton {\n"
"    background-color: rgb(255, 255, 255);\n"
"    border-radius: 10px;\n"
"    padding: 5px;\n"
"    font: 75 18pt \"Georgia\";\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgba(231, 230, 230, 252); \n"
"    color: black;\n"
"};\n"
"\n"
"")
        self.pushButtonRating3.setObjectName("pushButtonRating3")
        self.verticalLayout_6.addWidget(self.frameResult3)
        self.frameResult4 = QtWidgets.QFrame(parent=self.frameResult)
        self.frameResult4.setStyleSheet("QFrame {\n"
"    background-color: rgba(0, 0, 0, 200);\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"QFrame:hover {\n"
"    background-color: rgba(0,0,0,150);\n"
"}\n"
"")
        self.frameResult4.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frameResult4.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frameResult4.setObjectName("frameResult4")
        self.labelRate4 = QtWidgets.QLabel(parent=self.frameResult4)
        self.labelRate4.setGeometry(QtCore.QRect(330, 220, 211, 51))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.labelRate4.setFont(font)
        self.labelRate4.setStyleSheet("background-color: transparent;\n"
"font: 75 14pt \"Georgia\";\n"
"COLOR: rgb(255, 255, 255);")
        self.labelRate4.setText("")
        self.labelRate4.setObjectName("labelRate4")
        self.labelFigure4 = QtWidgets.QLabel(parent=self.frameResult4)
        self.labelFigure4.setGeometry(QtCore.QRect(10, 15, 250, 251))
        font = QtGui.QFont()
        font.setFamily("Sitka Text")
        font.setPointSize(10)
        self.labelFigure4.setFont(font)
        self.labelFigure4.setStyleSheet("background-color: transparent;\n"
"border-radius: 10px;")
        self.labelFigure4.setText("")
        self.labelFigure4.setObjectName("labelFigure4")
        self.labelLocation4 = QtWidgets.QLabel(parent=self.frameResult4)
        self.labelLocation4.setGeometry(QtCore.QRect(330, 80, 751, 51))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.labelLocation4.setFont(font)
        self.labelLocation4.setStyleSheet("background-color: transparent;\n"
"font: 75 14pt \"Georgia\";\n"
"COLOR: rgb(255, 255, 255);")
        self.labelLocation4.setText("")
        self.labelLocation4.setObjectName("labelLocation4")
        self.labelCategories4 = QtWidgets.QLabel(parent=self.frameResult4)
        self.labelCategories4.setGeometry(QtCore.QRect(330, 150, 751, 51))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.labelCategories4.setFont(font)
        self.labelCategories4.setStyleSheet("background-color: transparent;\n"
"font: 75 14pt \"Georgia\";\n"
"COLOR: rgb(255, 255, 255);")
        self.labelCategories4.setText("")
        self.labelCategories4.setObjectName("labelCategories4")
        self.labelRateIcon4 = QtWidgets.QLabel(parent=self.frameResult4)
        self.labelRateIcon4.setGeometry(QtCore.QRect(280, 225, 41, 41))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(30)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.labelRateIcon4.setFont(font)
        self.labelRateIcon4.setStyleSheet("font: 30pt \"MS Shell Dlg 2\";\n"
"COLOR:rgb(255, 255, 255); background-color: transparent")
        self.labelRateIcon4.setScaledContents(True)
        self.labelRateIcon4.setObjectName("labelRateIcon4")
        self.labelMessage4 = QtWidgets.QLabel(parent=self.frameResult4)
        self.labelMessage4.setGeometry(QtCore.QRect(280, 160, 41, 41))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(23)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.labelMessage4.setFont(font)
        self.labelMessage4.setStyleSheet("font: 23pt \"MS Shell Dlg 2\";\n"
"COLOR:rgb(255, 255, 255); background-color: transparent")
        self.labelMessage4.setScaledContents(True)
        self.labelMessage4.setObjectName("labelMessage4")
        self.labelLocationIcon4 = QtWidgets.QLabel(parent=self.frameResult4)
        self.labelLocationIcon4.setGeometry(QtCore.QRect(280, 90, 41, 41))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(23)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.labelLocationIcon4.setFont(font)
        self.labelLocationIcon4.setStyleSheet("font: 23pt \"MS Shell Dlg 2\";\n"
"COLOR:rgb(255, 255, 255); background-color: transparent")
        self.labelLocationIcon4.setScaledContents(True)
        self.labelLocationIcon4.setObjectName("labelLocationIcon4")
        self.labelName4 = QtWidgets.QLabel(parent=self.frameResult4)
        self.labelName4.setGeometry(QtCore.QRect(280, 10, 801, 61))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.labelName4.setFont(font)
        self.labelName4.setStyleSheet("background-color: transparent;\n"
"font: 75 18pt \"Georgia\";\n"
"COLOR: rgb(255, 255, 255);")
        self.labelName4.setText("")
        self.labelName4.setObjectName("labelName4")
        self.pushButtonRating4 = QtWidgets.QPushButton(parent=self.frameResult4)
        self.pushButtonRating4.setGeometry(QtCore.QRect(890, 220, 181, 51))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.pushButtonRating4.setFont(font)
        self.pushButtonRating4.setStyleSheet("\n"
"QPushButton {\n"
"    background-color: rgb(255, 255, 255);\n"
"    border-radius: 10px;\n"
"    padding: 5px;\n"
"    font: 75 18pt \"Georgia\";\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgba(231, 230, 230, 252); \n"
"    color: black;\n"
"};\n"
"\n"
"")
        self.pushButtonRating4.setObjectName("pushButtonRating4")
        self.verticalLayout_6.addWidget(self.frameResult4)
        self.frameResult5 = QtWidgets.QFrame(parent=self.frameResult)
        self.frameResult5.setStyleSheet("QFrame {\n"
"    background-color: rgba(0, 0, 0, 200);\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"QFrame:hover {\n"
"    background-color: rgba(0,0,0,150);\n"
"}\n"
"")
        self.frameResult5.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frameResult5.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frameResult5.setObjectName("frameResult5")
        self.labelRate5 = QtWidgets.QLabel(parent=self.frameResult5)
        self.labelRate5.setGeometry(QtCore.QRect(330, 220, 211, 51))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.labelRate5.setFont(font)
        self.labelRate5.setStyleSheet("background-color: transparent;\n"
"font: 75 14pt \"Georgia\";\n"
"COLOR: rgb(255, 255, 255);")
        self.labelRate5.setText("")
        self.labelRate5.setObjectName("labelRate5")
        self.labelFigure5 = QtWidgets.QLabel(parent=self.frameResult5)
        self.labelFigure5.setGeometry(QtCore.QRect(10, 15, 250, 251))
        font = QtGui.QFont()
        font.setFamily("Sitka Text")
        font.setPointSize(10)
        self.labelFigure5.setFont(font)
        self.labelFigure5.setStyleSheet("background-color: transparent;\n"
"border-radius: 10px;")
        self.labelFigure5.setText("")
        self.labelFigure5.setObjectName("labelFigure5")
        self.labelLocation5 = QtWidgets.QLabel(parent=self.frameResult5)
        self.labelLocation5.setGeometry(QtCore.QRect(330, 80, 751, 51))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.labelLocation5.setFont(font)
        self.labelLocation5.setStyleSheet("background-color: transparent;\n"
"font: 75 14pt \"Georgia\";\n"
"COLOR: rgb(255, 255, 255);")
        self.labelLocation5.setText("")
        self.labelLocation5.setObjectName("labelLocation5")
        self.labelCategories5 = QtWidgets.QLabel(parent=self.frameResult5)
        self.labelCategories5.setGeometry(QtCore.QRect(330, 150, 751, 51))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.labelCategories5.setFont(font)
        self.labelCategories5.setStyleSheet("background-color: transparent;\n"
"font: 75 14pt \"Georgia\";\n"
"COLOR: rgb(255, 255, 255);")
        self.labelCategories5.setText("")
        self.labelCategories5.setObjectName("labelCategories5")
        self.labelRateIcon5 = QtWidgets.QLabel(parent=self.frameResult5)
        self.labelRateIcon5.setGeometry(QtCore.QRect(280, 225, 41, 41))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(30)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.labelRateIcon5.setFont(font)
        self.labelRateIcon5.setStyleSheet("font: 30pt \"MS Shell Dlg 2\";\n"
"COLOR:rgb(255, 255, 255); background-color: transparent")
        self.labelRateIcon5.setScaledContents(True)
        self.labelRateIcon5.setObjectName("labelRateIcon5")
        self.labelMessage5 = QtWidgets.QLabel(parent=self.frameResult5)
        self.labelMessage5.setGeometry(QtCore.QRect(280, 160, 41, 41))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(23)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.labelMessage5.setFont(font)
        self.labelMessage5.setStyleSheet("font: 23pt \"MS Shell Dlg 2\";\n"
"COLOR:rgb(255, 255, 255); background-color: transparent")
        self.labelMessage5.setScaledContents(True)
        self.labelMessage5.setObjectName("labelMessage5")
        self.labelLocationIcon5 = QtWidgets.QLabel(parent=self.frameResult5)
        self.labelLocationIcon5.setGeometry(QtCore.QRect(280, 90, 41, 41))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(23)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.labelLocationIcon5.setFont(font)
        self.labelLocationIcon5.setStyleSheet("font: 23pt \"MS Shell Dlg 2\";\n"
"COLOR:rgb(255, 255, 255); background-color: transparent")
        self.labelLocationIcon5.setScaledContents(True)
        self.labelLocationIcon5.setObjectName("labelLocationIcon5")
        self.labelName5 = QtWidgets.QLabel(parent=self.frameResult5)
        self.labelName5.setGeometry(QtCore.QRect(280, 10, 801, 61))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.labelName5.setFont(font)
        self.labelName5.setStyleSheet("background-color: transparent;\n"
"font: 75 18pt \"Georgia\";\n"
"COLOR: rgb(255, 255, 255);")
        self.labelName5.setText("")
        self.labelName5.setObjectName("labelName5")
        self.pushButtonRating5 = QtWidgets.QPushButton(parent=self.frameResult5)
        self.pushButtonRating5.setGeometry(QtCore.QRect(890, 220, 181, 51))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.pushButtonRating5.setFont(font)
        self.pushButtonRating5.setStyleSheet("\n"
"QPushButton {\n"
"    background-color: rgb(255, 255, 255);\n"
"    border-radius: 10px;\n"
"    padding: 5px;\n"
"    font: 75 18pt \"Georgia\";\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgba(231, 230, 230, 252); \n"
"    color: black;\n"
"};\n"
"\n"
"")
        self.pushButtonRating5.setObjectName("pushButtonRating5")
        self.verticalLayout_6.addWidget(self.frameResult5)
        self.frameResult6 = QtWidgets.QFrame(parent=self.frameResult)
        self.frameResult6.setStyleSheet("QFrame {\n"
"    background-color: rgba(0, 0, 0, 200);\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"QFrame:hover {\n"
"    background-color: rgba(0,0,0,150);\n"
"}\n"
"")
        self.frameResult6.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frameResult6.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frameResult6.setObjectName("frameResult6")
        self.labelRate6 = QtWidgets.QLabel(parent=self.frameResult6)
        self.labelRate6.setGeometry(QtCore.QRect(330, 220, 211, 51))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.labelRate6.setFont(font)
        self.labelRate6.setStyleSheet("background-color: transparent;\n"
"font: 75 14pt \"Georgia\";\n"
"COLOR: rgb(255, 255, 255);")
        self.labelRate6.setText("")
        self.labelRate6.setObjectName("labelRate6")
        self.labelFigure6 = QtWidgets.QLabel(parent=self.frameResult6)
        self.labelFigure6.setGeometry(QtCore.QRect(10, 15, 250, 251))
        font = QtGui.QFont()
        font.setFamily("Sitka Text")
        font.setPointSize(10)
        self.labelFigure6.setFont(font)
        self.labelFigure6.setStyleSheet("background-color: transparent;\n"
"border-radius: 10px;")
        self.labelFigure6.setText("")
        self.labelFigure6.setObjectName("labelFigure6")
        self.labelLocation6 = QtWidgets.QLabel(parent=self.frameResult6)
        self.labelLocation6.setGeometry(QtCore.QRect(330, 80, 751, 51))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.labelLocation6.setFont(font)
        self.labelLocation6.setStyleSheet("background-color: transparent;\n"
"font: 75 14pt \"Georgia\";\n"
"COLOR: rgb(255, 255, 255);")
        self.labelLocation6.setText("")
        self.labelLocation6.setObjectName("labelLocation6")
        self.labelCategories6 = QtWidgets.QLabel(parent=self.frameResult6)
        self.labelCategories6.setGeometry(QtCore.QRect(330, 150, 751, 51))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.labelCategories6.setFont(font)
        self.labelCategories6.setStyleSheet("background-color: transparent;\n"
"font: 75 14pt \"Georgia\";\n"
"COLOR: rgb(255, 255, 255);")
        self.labelCategories6.setText("")
        self.labelCategories6.setObjectName("labelCategories6")
        self.labelRateIcon6 = QtWidgets.QLabel(parent=self.frameResult6)
        self.labelRateIcon6.setGeometry(QtCore.QRect(280, 225, 41, 41))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(30)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.labelRateIcon6.setFont(font)
        self.labelRateIcon6.setStyleSheet("font: 30pt \"MS Shell Dlg 2\";\n"
"COLOR:rgb(255, 255, 255); background-color: transparent")
        self.labelRateIcon6.setScaledContents(True)
        self.labelRateIcon6.setObjectName("labelRateIcon6")
        self.labelMessage6 = QtWidgets.QLabel(parent=self.frameResult6)
        self.labelMessage6.setGeometry(QtCore.QRect(280, 160, 41, 41))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(23)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.labelMessage6.setFont(font)
        self.labelMessage6.setStyleSheet("font: 23pt \"MS Shell Dlg 2\";\n"
"COLOR:rgb(255, 255, 255); background-color: transparent")
        self.labelMessage6.setScaledContents(True)
        self.labelMessage6.setObjectName("labelMessage6")
        self.labelLocationIcon6 = QtWidgets.QLabel(parent=self.frameResult6)
        self.labelLocationIcon6.setGeometry(QtCore.QRect(280, 90, 41, 41))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(23)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.labelLocationIcon6.setFont(font)
        self.labelLocationIcon6.setStyleSheet("font: 23pt \"MS Shell Dlg 2\";\n"
"COLOR:rgb(255, 255, 255); background-color: transparent")
        self.labelLocationIcon6.setScaledContents(True)
        self.labelLocationIcon6.setObjectName("labelLocationIcon6")
        self.labelName6 = QtWidgets.QLabel(parent=self.frameResult6)
        self.labelName6.setGeometry(QtCore.QRect(280, 10, 801, 61))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.labelName6.setFont(font)
        self.labelName6.setStyleSheet("background-color: transparent;\n"
"font: 75 18pt \"Georgia\";\n"
"COLOR: rgb(255, 255, 255);")
        self.labelName6.setText("")
        self.labelName6.setObjectName("labelName6")
        self.pushButtonRating6 = QtWidgets.QPushButton(parent=self.frameResult6)
        self.pushButtonRating6.setGeometry(QtCore.QRect(890, 220, 181, 51))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.pushButtonRating6.setFont(font)
        self.pushButtonRating6.setStyleSheet("\n"
"QPushButton {\n"
"    background-color: rgb(255, 255, 255);\n"
"    border-radius: 10px;\n"
"    padding: 5px;\n"
"    font: 75 18pt \"Georgia\";\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgba(231, 230, 230, 252); \n"
"    color: black;\n"
"};\n"
"\n"
"")
        self.pushButtonRating6.setObjectName("pushButtonRating6")
        self.verticalLayout_6.addWidget(self.frameResult6)
        self.frameResult7 = QtWidgets.QFrame(parent=self.frameResult)
        self.frameResult7.setStyleSheet("QFrame {\n"
"    background-color: rgba(0, 0, 0, 200);\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"QFrame:hover {\n"
"    background-color: rgba(0,0,0,150);\n"
"}\n"
"")
        self.frameResult7.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frameResult7.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frameResult7.setObjectName("frameResult7")
        self.labelRate7 = QtWidgets.QLabel(parent=self.frameResult7)
        self.labelRate7.setGeometry(QtCore.QRect(330, 220, 211, 51))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.labelRate7.setFont(font)
        self.labelRate7.setStyleSheet("background-color: transparent;\n"
"font: 75 14pt \"Georgia\";\n"
"COLOR: rgb(255, 255, 255);")
        self.labelRate7.setText("")
        self.labelRate7.setObjectName("labelRate7")
        self.labelFigure7 = QtWidgets.QLabel(parent=self.frameResult7)
        self.labelFigure7.setGeometry(QtCore.QRect(10, 15, 250, 251))
        font = QtGui.QFont()
        font.setFamily("Sitka Text")
        font.setPointSize(10)
        self.labelFigure7.setFont(font)
        self.labelFigure7.setStyleSheet("background-color: transparent;\n"
"border-radius: 10px;")
        self.labelFigure7.setText("")
        self.labelFigure7.setObjectName("labelFigure7")
        self.labelLocation7 = QtWidgets.QLabel(parent=self.frameResult7)
        self.labelLocation7.setGeometry(QtCore.QRect(330, 80, 751, 51))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.labelLocation7.setFont(font)
        self.labelLocation7.setStyleSheet("background-color: transparent;\n"
"font: 75 14pt \"Georgia\";\n"
"COLOR: rgb(255, 255, 255);")
        self.labelLocation7.setText("")
        self.labelLocation7.setObjectName("labelLocation7")
        self.labelCategories7 = QtWidgets.QLabel(parent=self.frameResult7)
        self.labelCategories7.setGeometry(QtCore.QRect(330, 150, 751, 51))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.labelCategories7.setFont(font)
        self.labelCategories7.setStyleSheet("background-color: transparent;\n"
"font: 75 14pt \"Georgia\";\n"
"COLOR: rgb(255, 255, 255);")
        self.labelCategories7.setText("")
        self.labelCategories7.setObjectName("labelCategories7")
        self.labelRateIcon7 = QtWidgets.QLabel(parent=self.frameResult7)
        self.labelRateIcon7.setGeometry(QtCore.QRect(280, 225, 41, 41))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(30)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.labelRateIcon7.setFont(font)
        self.labelRateIcon7.setStyleSheet("font: 30pt \"MS Shell Dlg 2\";\n"
"COLOR:rgb(255, 255, 255); background-color: transparent")
        self.labelRateIcon7.setScaledContents(True)
        self.labelRateIcon7.setObjectName("labelRateIcon7")
        self.labelMessage7 = QtWidgets.QLabel(parent=self.frameResult7)
        self.labelMessage7.setGeometry(QtCore.QRect(280, 160, 41, 41))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(23)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.labelMessage7.setFont(font)
        self.labelMessage7.setStyleSheet("font: 23pt \"MS Shell Dlg 2\";\n"
"COLOR:rgb(255, 255, 255); background-color: transparent")
        self.labelMessage7.setScaledContents(True)
        self.labelMessage7.setObjectName("labelMessage7")
        self.labelLocationIcon7 = QtWidgets.QLabel(parent=self.frameResult7)
        self.labelLocationIcon7.setGeometry(QtCore.QRect(280, 90, 41, 41))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(23)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.labelLocationIcon7.setFont(font)
        self.labelLocationIcon7.setStyleSheet("font: 23pt \"MS Shell Dlg 2\";\n"
"COLOR:rgb(255, 255, 255); background-color: transparent")
        self.labelLocationIcon7.setScaledContents(True)
        self.labelLocationIcon7.setObjectName("labelLocationIcon7")
        self.labelName7 = QtWidgets.QLabel(parent=self.frameResult7)
        self.labelName7.setGeometry(QtCore.QRect(280, 10, 801, 61))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.labelName7.setFont(font)
        self.labelName7.setStyleSheet("background-color: transparent;\n"
"font: 75 18pt \"Georgia\";\n"
"COLOR: rgb(255, 255, 255);")
        self.labelName7.setText("")
        self.labelName7.setObjectName("labelName7")
        self.pushButtonRating7 = QtWidgets.QPushButton(parent=self.frameResult7)
        self.pushButtonRating7.setGeometry(QtCore.QRect(890, 220, 181, 51))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.pushButtonRating7.setFont(font)
        self.pushButtonRating7.setStyleSheet("\n"
"QPushButton {\n"
"    background-color: rgb(255, 255, 255);\n"
"    border-radius: 10px;\n"
"    padding: 5px;\n"
"    font: 75 18pt \"Georgia\";\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgba(231, 230, 230, 252); \n"
"    color: black;\n"
"};\n"
"\n"
"")
        self.pushButtonRating7.setObjectName("pushButtonRating7")
        self.verticalLayout_6.addWidget(self.frameResult7)
        self.frameResult8 = QtWidgets.QFrame(parent=self.frameResult)
        self.frameResult8.setStyleSheet("QFrame {\n"
"    background-color: rgba(0, 0, 0, 200);\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"QFrame:hover {\n"
"    background-color: rgba(0,0,0,150);\n"
"}\n"
"")
        self.frameResult8.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frameResult8.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frameResult8.setObjectName("frameResult8")
        self.labelRate8 = QtWidgets.QLabel(parent=self.frameResult8)
        self.labelRate8.setGeometry(QtCore.QRect(330, 220, 211, 51))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.labelRate8.setFont(font)
        self.labelRate8.setStyleSheet("background-color: transparent;\n"
"font: 75 14pt \"Georgia\";\n"
"COLOR: rgb(255, 255, 255);")
        self.labelRate8.setText("")
        self.labelRate8.setObjectName("labelRate8")
        self.labelFigure8 = QtWidgets.QLabel(parent=self.frameResult8)
        self.labelFigure8.setGeometry(QtCore.QRect(10, 15, 250, 251))
        font = QtGui.QFont()
        font.setFamily("Sitka Text")
        font.setPointSize(10)
        self.labelFigure8.setFont(font)
        self.labelFigure8.setStyleSheet("background-color: transparent;\n"
"border-radius: 10px;")
        self.labelFigure8.setText("")
        self.labelFigure8.setObjectName("labelFigure8")
        self.labelLocation8 = QtWidgets.QLabel(parent=self.frameResult8)
        self.labelLocation8.setGeometry(QtCore.QRect(330, 80, 751, 51))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.labelLocation8.setFont(font)
        self.labelLocation8.setStyleSheet("background-color: transparent;\n"
"font: 75 14pt \"Georgia\";\n"
"COLOR: rgb(255, 255, 255);")
        self.labelLocation8.setText("")
        self.labelLocation8.setObjectName("labelLocation8")
        self.labelCategories8 = QtWidgets.QLabel(parent=self.frameResult8)
        self.labelCategories8.setGeometry(QtCore.QRect(330, 150, 751, 51))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.labelCategories8.setFont(font)
        self.labelCategories8.setStyleSheet("background-color: transparent;\n"
"font: 75 14pt \"Georgia\";\n"
"COLOR: rgb(255, 255, 255);")
        self.labelCategories8.setText("")
        self.labelCategories8.setObjectName("labelCategories8")
        self.labelRateIcon8 = QtWidgets.QLabel(parent=self.frameResult8)
        self.labelRateIcon8.setGeometry(QtCore.QRect(280, 225, 41, 41))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(30)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.labelRateIcon8.setFont(font)
        self.labelRateIcon8.setStyleSheet("font: 30pt \"MS Shell Dlg 2\";\n"
"COLOR:rgb(255, 255, 255); background-color: transparent")
        self.labelRateIcon8.setScaledContents(True)
        self.labelRateIcon8.setObjectName("labelRateIcon8")
        self.labelMessage8 = QtWidgets.QLabel(parent=self.frameResult8)
        self.labelMessage8.setGeometry(QtCore.QRect(280, 160, 41, 41))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(23)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.labelMessage8.setFont(font)
        self.labelMessage8.setStyleSheet("font: 23pt \"MS Shell Dlg 2\";\n"
"COLOR:rgb(255, 255, 255); background-color: transparent")
        self.labelMessage8.setScaledContents(True)
        self.labelMessage8.setObjectName("labelMessage8")
        self.labelLocationIcon8 = QtWidgets.QLabel(parent=self.frameResult8)
        self.labelLocationIcon8.setGeometry(QtCore.QRect(280, 90, 41, 41))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(23)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.labelLocationIcon8.setFont(font)
        self.labelLocationIcon8.setStyleSheet("font: 23pt \"MS Shell Dlg 2\";\n"
"COLOR:rgb(255, 255, 255); background-color: transparent")
        self.labelLocationIcon8.setScaledContents(True)
        self.labelLocationIcon8.setObjectName("labelLocationIcon8")
        self.labelName8 = QtWidgets.QLabel(parent=self.frameResult8)
        self.labelName8.setGeometry(QtCore.QRect(280, 10, 801, 61))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.labelName8.setFont(font)
        self.labelName8.setStyleSheet("background-color: transparent;\n"
"font: 75 18pt \"Georgia\";\n"
"COLOR: rgb(255, 255, 255);")
        self.labelName8.setText("")
        self.labelName8.setObjectName("labelName8")
        self.pushButtonRating8 = QtWidgets.QPushButton(parent=self.frameResult8)
        self.pushButtonRating8.setGeometry(QtCore.QRect(890, 220, 181, 51))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.pushButtonRating8.setFont(font)
        self.pushButtonRating8.setStyleSheet("\n"
"QPushButton {\n"
"    background-color: rgb(255, 255, 255);\n"
"    border-radius: 10px;\n"
"    padding: 5px;\n"
"    font: 75 18pt \"Georgia\";\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgba(231, 230, 230, 252); \n"
"    color: black;\n"
"};\n"
"\n"
"")
        self.pushButtonRating8.setObjectName("pushButtonRating8")
        self.verticalLayout_6.addWidget(self.frameResult8)
        self.frameResult9 = QtWidgets.QFrame(parent=self.frameResult)
        self.frameResult9.setStyleSheet("QFrame {\n"
"    background-color: rgba(0, 0, 0, 200);\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"QFrame:hover {\n"
"    background-color: rgba(0,0,0,150);\n"
"}\n"
"")
        self.frameResult9.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frameResult9.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frameResult9.setObjectName("frameResult9")
        self.labelRate9 = QtWidgets.QLabel(parent=self.frameResult9)
        self.labelRate9.setGeometry(QtCore.QRect(330, 220, 211, 51))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.labelRate9.setFont(font)
        self.labelRate9.setStyleSheet("background-color: transparent;\n"
"font: 75 14pt \"Georgia\";\n"
"COLOR: rgb(255, 255, 255);")
        self.labelRate9.setText("")
        self.labelRate9.setObjectName("labelRate9")
        self.labelFigure9 = QtWidgets.QLabel(parent=self.frameResult9)
        self.labelFigure9.setGeometry(QtCore.QRect(10, 15, 250, 251))
        font = QtGui.QFont()
        font.setFamily("Sitka Text")
        font.setPointSize(10)
        self.labelFigure9.setFont(font)
        self.labelFigure9.setStyleSheet("background-color: transparent;\n"
"border-radius: 10px;")
        self.labelFigure9.setText("")
        self.labelFigure9.setObjectName("labelFigure9")
        self.labelLocation9 = QtWidgets.QLabel(parent=self.frameResult9)
        self.labelLocation9.setGeometry(QtCore.QRect(330, 80, 751, 51))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.labelLocation9.setFont(font)
        self.labelLocation9.setStyleSheet("background-color: transparent;\n"
"font: 75 14pt \"Georgia\";\n"
"COLOR: rgb(255, 255, 255);")
        self.labelLocation9.setText("")
        self.labelLocation9.setObjectName("labelLocation9")
        self.labelCategories9 = QtWidgets.QLabel(parent=self.frameResult9)
        self.labelCategories9.setGeometry(QtCore.QRect(330, 150, 751, 51))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.labelCategories9.setFont(font)
        self.labelCategories9.setStyleSheet("background-color: transparent;\n"
"font: 75 14pt \"Georgia\";\n"
"COLOR: rgb(255, 255, 255);")
        self.labelCategories9.setText("")
        self.labelCategories9.setObjectName("labelCategories9")
        self.labelRateIcon9 = QtWidgets.QLabel(parent=self.frameResult9)
        self.labelRateIcon9.setGeometry(QtCore.QRect(280, 225, 41, 41))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(30)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.labelRateIcon9.setFont(font)
        self.labelRateIcon9.setStyleSheet("font: 30pt \"MS Shell Dlg 2\";\n"
"COLOR:rgb(255, 255, 255); background-color: transparent")
        self.labelRateIcon9.setScaledContents(True)
        self.labelRateIcon9.setObjectName("labelRateIcon9")
        self.labelMessage9 = QtWidgets.QLabel(parent=self.frameResult9)
        self.labelMessage9.setGeometry(QtCore.QRect(280, 160, 41, 41))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(23)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.labelMessage9.setFont(font)
        self.labelMessage9.setStyleSheet("font: 23pt \"MS Shell Dlg 2\";\n"
"COLOR:rgb(255, 255, 255); background-color: transparent")
        self.labelMessage9.setScaledContents(True)
        self.labelMessage9.setObjectName("labelMessage9")
        self.labelLocationIcon9 = QtWidgets.QLabel(parent=self.frameResult9)
        self.labelLocationIcon9.setGeometry(QtCore.QRect(280, 90, 41, 41))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(23)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.labelLocationIcon9.setFont(font)
        self.labelLocationIcon9.setStyleSheet("font: 23pt \"MS Shell Dlg 2\";\n"
"COLOR:rgb(255, 255, 255); background-color: transparent")
        self.labelLocationIcon9.setScaledContents(True)
        self.labelLocationIcon9.setObjectName("labelLocationIcon9")
        self.labelName9 = QtWidgets.QLabel(parent=self.frameResult9)
        self.labelName9.setGeometry(QtCore.QRect(280, 10, 801, 61))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.labelName9.setFont(font)
        self.labelName9.setStyleSheet("background-color: transparent;\n"
"font: 75 18pt \"Georgia\";\n"
"COLOR: rgb(255, 255, 255);")
        self.labelName9.setText("")
        self.labelName9.setObjectName("labelName9")
        self.pushButtonRating9 = QtWidgets.QPushButton(parent=self.frameResult9)
        self.pushButtonRating9.setGeometry(QtCore.QRect(890, 220, 181, 51))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.pushButtonRating9.setFont(font)
        self.pushButtonRating9.setStyleSheet("\n"
"QPushButton {\n"
"    background-color: rgb(255, 255, 255);\n"
"    border-radius: 10px;\n"
"    padding: 5px;\n"
"    font: 75 18pt \"Georgia\";\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgba(231, 230, 230, 252); \n"
"    color: black;\n"
"};\n"
"\n"
"")
        self.pushButtonRating9.setObjectName("pushButtonRating9")
        self.verticalLayout_6.addWidget(self.frameResult9)
        self.frameResult10 = QtWidgets.QFrame(parent=self.frameResult)
        self.frameResult10.setStyleSheet("QFrame {\n"
"    background-color: rgba(0, 0, 0, 200);\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"QFrame:hover {\n"
"    background-color: rgba(0,0,0,150);\n"
"}\n"
"")
        self.frameResult10.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frameResult10.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frameResult10.setObjectName("frameResult10")
        self.labelRate10 = QtWidgets.QLabel(parent=self.frameResult10)
        self.labelRate10.setGeometry(QtCore.QRect(330, 220, 211, 51))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.labelRate10.setFont(font)
        self.labelRate10.setStyleSheet("background-color: transparent;\n"
"font: 75 14pt \"Georgia\";\n"
"COLOR: rgb(255, 255, 255);")
        self.labelRate10.setText("")
        self.labelRate10.setObjectName("labelRate10")
        self.labelFigure10 = QtWidgets.QLabel(parent=self.frameResult10)
        self.labelFigure10.setGeometry(QtCore.QRect(10, 15, 250, 251))
        font = QtGui.QFont()
        font.setFamily("Sitka Text")
        font.setPointSize(10)
        self.labelFigure10.setFont(font)
        self.labelFigure10.setStyleSheet("background-color: transparent;\n"
"border-radius: 10px;")
        self.labelFigure10.setText("")
        self.labelFigure10.setObjectName("labelFigure10")
        self.labelLocation10 = QtWidgets.QLabel(parent=self.frameResult10)
        self.labelLocation10.setGeometry(QtCore.QRect(330, 80, 751, 51))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.labelLocation10.setFont(font)
        self.labelLocation10.setStyleSheet("background-color: transparent;\n"
"font: 75 14pt \"Georgia\";\n"
"COLOR: rgb(255, 255, 255);")
        self.labelLocation10.setText("")
        self.labelLocation10.setObjectName("labelLocation10")
        self.labelCategories10 = QtWidgets.QLabel(parent=self.frameResult10)
        self.labelCategories10.setGeometry(QtCore.QRect(330, 150, 751, 51))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.labelCategories10.setFont(font)
        self.labelCategories10.setStyleSheet("background-color: transparent;\n"
"font: 75 14pt \"Georgia\";\n"
"COLOR: rgb(255, 255, 255);")
        self.labelCategories10.setText("")
        self.labelCategories10.setObjectName("labelCategories10")
        self.labelRateIcon10 = QtWidgets.QLabel(parent=self.frameResult10)
        self.labelRateIcon10.setGeometry(QtCore.QRect(280, 225, 41, 41))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(30)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.labelRateIcon10.setFont(font)
        self.labelRateIcon10.setStyleSheet("font: 30pt \"MS Shell Dlg 2\";\n"
"COLOR:rgb(255, 255, 255); background-color: transparent")
        self.labelRateIcon10.setScaledContents(True)
        self.labelRateIcon10.setObjectName("labelRateIcon10")
        self.labelMessage10 = QtWidgets.QLabel(parent=self.frameResult10)
        self.labelMessage10.setGeometry(QtCore.QRect(280, 160, 41, 41))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(23)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.labelMessage10.setFont(font)
        self.labelMessage10.setStyleSheet("font: 23pt \"MS Shell Dlg 2\";\n"
"COLOR:rgb(255, 255, 255); background-color: transparent")
        self.labelMessage10.setScaledContents(True)
        self.labelMessage10.setObjectName("labelMessage10")
        self.labelLocationIcon10 = QtWidgets.QLabel(parent=self.frameResult10)
        self.labelLocationIcon10.setGeometry(QtCore.QRect(280, 90, 41, 41))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(23)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.labelLocationIcon10.setFont(font)
        self.labelLocationIcon10.setStyleSheet("font: 23pt \"MS Shell Dlg 2\";\n"
"COLOR:rgb(255, 255, 255); background-color: transparent")
        self.labelLocationIcon10.setScaledContents(True)
        self.labelLocationIcon10.setObjectName("labelLocationIcon10")
        self.labelName10 = QtWidgets.QLabel(parent=self.frameResult10)
        self.labelName10.setGeometry(QtCore.QRect(280, 10, 801, 61))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.labelName10.setFont(font)
        self.labelName10.setStyleSheet("background-color: transparent;\n"
"font: 75 18pt \"Georgia\";\n"
"COLOR: rgb(255, 255, 255);")
        self.labelName10.setText("")
        self.labelName10.setObjectName("labelName10")
        self.pushButtonRating10 = QtWidgets.QPushButton(parent=self.frameResult10)
        self.pushButtonRating10.setGeometry(QtCore.QRect(890, 220, 181, 51))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.pushButtonRating10.setFont(font)
        self.pushButtonRating10.setStyleSheet("\n"
"QPushButton {\n"
"    background-color: rgb(255, 255, 255);\n"
"    border-radius: 10px;\n"
"    padding: 5px;\n"
"    font: 75 18pt \"Georgia\";\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgba(231, 230, 230, 252); \n"
"    color: black;\n"
"};\n"
"\n"
"")
        self.pushButtonRating10.setObjectName("pushButtonRating10")
        self.verticalLayout_6.addWidget(self.frameResult10)
        self.labelSponsoredResult = QtWidgets.QLabel(parent=self.widget)
        self.labelSponsoredResult.setGeometry(QtCore.QRect(130, 120, 281, 51))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(24)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        font.setStyleStrategy(QtGui.QFont.StyleStrategy.PreferDefault)
        self.labelSponsoredResult.setFont(font)
        self.labelSponsoredResult.setStyleSheet("COLOR: rgb(255, 255, 255)")
        self.labelSponsoredResult.setObjectName("labelSponsoredResult")
        self.labelTitle = QtWidgets.QLabel(parent=self.widget)
        self.labelTitle.setGeometry(QtCore.QRect(370, 40, 751, 71))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(30)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        font.setStyleStrategy(QtGui.QFont.StyleStrategy.PreferDefault)
        self.labelTitle.setFont(font)
        self.labelTitle.setStyleSheet("COLOR: rgb(255, 255, 255)\n"
"")
        self.labelTitle.setObjectName("labelTitle")
        self.pushButtonextpage = QtWidgets.QPushButton(parent=self.widget)
        self.pushButtonextpage.setGeometry(QtCore.QRect(1100, 120, 181, 51))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.pushButtonextpage.setFont(font)
        self.pushButtonextpage.setStyleSheet("\n"
"QPushButton {\n"
"    background-color: rgb(255, 255, 255);\n"
"    border-radius: 10px;\n"
"    padding: 5px;\n"
"    font: 75 18pt \"Georgia\";\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgba(231, 230, 230, 252); \n"
"    color: black;\n"
"};\n"
"\n"
"")
        self.pushButtonextpage.setObjectName("pushButtonextpage")
        self.verticalLayout_5.addWidget(self.frameMain)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_4.addWidget(self.scrollArea)
        self.labelBackground = QtWidgets.QLabel(parent=self.centralwidget)
        self.labelBackground.setGeometry(QtCore.QRect(0, -51, 1500, 961))
        self.labelBackground.setStyleSheet("")
        self.labelBackground.setText("")
        self.labelBackground.setPixmap(QtGui.QPixmap("C:\\Users\\OS\\LAVY\\LAVY_FINALPROJECT\\UI\\../Images/background.jpg"))
        self.labelBackground.setScaledContents(True)
        self.labelBackground.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.labelBackground.setObjectName("labelBackground")
        self.labelBackground.raise_()
        self.TitleBar.raise_()
        self.widgetBGMain.raise_()
        HomePageAfterRating.setCentralWidget(self.centralwidget)

        self.retranslateUi(HomePageAfterRating)
        QtCore.QMetaObject.connectSlotsByName(HomePageAfterRating)

    def retranslateUi(self, HomePageAfterRating):
        _translate = QtCore.QCoreApplication.translate
        HomePageAfterRating.setWindowTitle(_translate("HomePageAfterRating", "MainWindow"))
        self.lineEditSearch.setWhatsThis(_translate("HomePageAfterRating", "<html><head/><body><p><br/></p></body></html>"))
        self.lineEditSearch.setPlaceholderText(_translate("HomePageAfterRating", "Search for the restaurant..."))
        self.pushButtonWriteReview.setText(_translate("HomePageAfterRating", "Write a review"))
        self.pushButtonLogOut.setText(_translate("HomePageAfterRating", "Log Out"))
        self.labelValy.setText(_translate("HomePageAfterRating", "Valy"))
        self.labelRateIcon1.setText(_translate("HomePageAfterRating", "★"))
        self.labelMessage1.setText(_translate("HomePageAfterRating", "💬"))
        self.labelLocationIcon1.setText(_translate("HomePageAfterRating", "🌍"))
        self.pushButtonRating1.setText(_translate("HomePageAfterRating", "Rating"))
        self.labelRateIcon2.setText(_translate("HomePageAfterRating", "★"))
        self.labelMessage2.setText(_translate("HomePageAfterRating", "💬"))
        self.labelLocationIcon2.setText(_translate("HomePageAfterRating", "🌍"))
        self.pushButtonRating2.setText(_translate("HomePageAfterRating", "Rating"))
        self.labelRateIcon3.setText(_translate("HomePageAfterRating", "★"))
        self.labelMessage3.setText(_translate("HomePageAfterRating", "💬"))
        self.labelLocationIcon3.setText(_translate("HomePageAfterRating", "🌍"))
        self.pushButtonRating3.setText(_translate("HomePageAfterRating", "Rating"))
        self.labelRateIcon4.setText(_translate("HomePageAfterRating", "★"))
        self.labelMessage4.setText(_translate("HomePageAfterRating", "💬"))
        self.labelLocationIcon4.setText(_translate("HomePageAfterRating", "🌍"))
        self.pushButtonRating4.setText(_translate("HomePageAfterRating", "Rating"))
        self.labelRateIcon5.setText(_translate("HomePageAfterRating", "★"))
        self.labelMessage5.setText(_translate("HomePageAfterRating", "💬"))
        self.labelLocationIcon5.setText(_translate("HomePageAfterRating", "🌍"))
        self.pushButtonRating5.setText(_translate("HomePageAfterRating", "Rating"))
        self.labelRateIcon6.setText(_translate("HomePageAfterRating", "★"))
        self.labelMessage6.setText(_translate("HomePageAfterRating", "💬"))
        self.labelLocationIcon6.setText(_translate("HomePageAfterRating", "🌍"))
        self.pushButtonRating6.setText(_translate("HomePageAfterRating", "Rating"))
        self.labelRateIcon7.setText(_translate("HomePageAfterRating", "★"))
        self.labelMessage7.setText(_translate("HomePageAfterRating", "💬"))
        self.labelLocationIcon7.setText(_translate("HomePageAfterRating", "🌍"))
        self.pushButtonRating7.setText(_translate("HomePageAfterRating", "Rating"))
        self.labelRateIcon8.setText(_translate("HomePageAfterRating", "★"))
        self.labelMessage8.setText(_translate("HomePageAfterRating", "💬"))
        self.labelLocationIcon8.setText(_translate("HomePageAfterRating", "🌍"))
        self.pushButtonRating8.setText(_translate("HomePageAfterRating", "Rating"))
        self.labelRateIcon9.setText(_translate("HomePageAfterRating", "★"))
        self.labelMessage9.setText(_translate("HomePageAfterRating", "💬"))
        self.labelLocationIcon9.setText(_translate("HomePageAfterRating", "🌍"))
        self.pushButtonRating9.setText(_translate("HomePageAfterRating", "Rating"))
        self.labelRateIcon10.setText(_translate("HomePageAfterRating", "★"))
        self.labelMessage10.setText(_translate("HomePageAfterRating", "💬"))
        self.labelLocationIcon10.setText(_translate("HomePageAfterRating", "🌍"))
        self.pushButtonRating10.setText(_translate("HomePageAfterRating", "Rating"))
        self.labelSponsoredResult.setText(_translate("HomePageAfterRating", "Recommend"))
        self.labelTitle.setText(_translate("HomePageAfterRating", "Discover the recommendations just for you!"))
        self.pushButtonextpage.setText(_translate("HomePageAfterRating", "Next Page"))
