# Form implementation generated from reading ui file 'C:\Users\OS\LAVY\LAVY_FINALPROJECT\UI\Login.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(1500, 900)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.widgetMain = QtWidgets.QWidget(parent=self.centralwidget)
        self.widgetMain.setGeometry(QtCore.QRect(0, -1, 1500, 951))
        self.widgetMain.setObjectName("widgetMain")
        self.labelHomepagebackground = QtWidgets.QLabel(parent=self.widgetMain)
        self.labelHomepagebackground.setGeometry(QtCore.QRect(0, -10, 1500, 911))
        self.labelHomepagebackground.setStyleSheet("")
        self.labelHomepagebackground.setText("")
        self.labelHomepagebackground.setPixmap(QtGui.QPixmap("C:\\Users\\OS\\LAVY\\LAVY_FINALPROJECT\\UI\\../Images/backgroundlogin.jpg"))
        self.labelHomepagebackground.setScaledContents(True)
        self.labelHomepagebackground.setObjectName("labelHomepagebackground")
        self.labelBackground = QtWidgets.QLabel(parent=self.widgetMain)
        self.labelBackground.setGeometry(QtCore.QRect(0, -50, 1500, 961))
        self.labelBackground.setStyleSheet("background-color: rgba(0,0,0,150);\n"
"")
        self.labelBackground.setText("")
        self.labelBackground.setScaledContents(True)
        self.labelBackground.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.labelBackground.setObjectName("labelBackground")
        self.Main = QtWidgets.QWidget(parent=self.widgetMain)
        self.Main.setGeometry(QtCore.QRect(320, 150, 851, 611))
        self.Main.setObjectName("Main")
        self.labelMain = QtWidgets.QLabel(parent=self.Main)
        self.labelMain.setGeometry(QtCore.QRect(60, 0, 751, 611))
        self.labelMain.setStyleSheet("background-color: rgba(0,0,0,180);\n"
"border-radius:20px;")
        self.labelMain.setText("")
        self.labelMain.setObjectName("labelMain")
        self.labelLogin = QtWidgets.QLabel(parent=self.Main)
        self.labelLogin.setGeometry(QtCore.QRect(310, 60, 241, 101))
        font = QtGui.QFont()
        font.setFamily("VNI-Souvir")
        font.setPointSize(31)
        font.setStyleStrategy(QtGui.QFont.StyleStrategy.PreferAntialias)
        self.labelLogin.setFont(font)
        self.labelLogin.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.ArrowCursor))
        self.labelLogin.setStyleSheet("COLOR:rgb(240, 240, 240)")
        self.labelLogin.setScaledContents(True)
        self.labelLogin.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.labelLogin.setObjectName("labelLogin")
        self.lineEditUsername = QtWidgets.QLineEdit(parent=self.Main)
        self.lineEditUsername.setGeometry(QtCore.QRect(180, 190, 520, 51))
        self.lineEditUsername.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("VNI-Souvir")
        font.setPointSize(14)
        self.lineEditUsername.setFont(font)
        self.lineEditUsername.setStyleSheet("BACKGROUND-COLOR: transparent;\n"
"BORDER: NONE;\n"
"BORDER-BOTTOM: 2PX SOLID rgb(236, 236, 236);\n"
"COLOR:rgb(255, 255, 255);\n"
"padding-bottom:7px;")
        self.lineEditUsername.setText("")
        self.lineEditUsername.setObjectName("lineEditUsername")
        self.lineEditPassword = QtWidgets.QLineEdit(parent=self.Main)
        self.lineEditPassword.setGeometry(QtCore.QRect(180, 270, 520, 51))
        self.lineEditPassword.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("VNI-Souvir")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.lineEditPassword.setFont(font)
        self.lineEditPassword.setStyleSheet("BACKGROUND-COLOR: transparent;\n"
"BORDER: NONE;\n"
"BORDER-BOTTOM: 2PX SOLID rgb(236, 236, 236);\n"
"COLOR:rgb(255, 255, 255);\n"
"padding-bottom:7px;")
        self.lineEditPassword.setText("")
        self.lineEditPassword.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.lineEditPassword.setObjectName("lineEditPassword")
        self.pushButtonLogin = QtWidgets.QPushButton(parent=self.Main)
        self.pushButtonLogin.setGeometry(QtCore.QRect(310, 440, 231, 51))
        font = QtGui.QFont()
        font.setFamily("VNI-Souvir")
        font.setPointSize(15)
        self.pushButtonLogin.setFont(font)
        self.pushButtonLogin.setStyleSheet("background-color: rgb(248, 248, 248);\n"
"border-radius: 10px;\n"
"")
        self.pushButtonLogin.setCheckable(True)
        self.pushButtonLogin.setAutoDefault(False)
        self.pushButtonLogin.setObjectName("pushButtonLogin")
        self.labelForgetPassword = QtWidgets.QLabel(parent=self.Main)
        self.labelForgetPassword.setGeometry(QtCore.QRect(220, 510, 401, 21))
        font = QtGui.QFont()
        font.setFamily("VNI-Souvir")
        font.setPointSize(8)
        font.setStyleStrategy(QtGui.QFont.StyleStrategy.PreferAntialias)
        self.labelForgetPassword.setFont(font)
        self.labelForgetPassword.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.ArrowCursor))
        self.labelForgetPassword.setStyleSheet("COLOR:rgb(240, 240, 240)")
        self.labelForgetPassword.setScaledContents(True)
        self.labelForgetPassword.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.labelForgetPassword.setObjectName("labelForgetPassword")
        self.checkBoxSavePassword = QtWidgets.QCheckBox(parent=self.Main)
        self.checkBoxSavePassword.setGeometry(QtCore.QRect(180, 360, 331, 21))
        font = QtGui.QFont()
        font.setFamily("VNI-Souvir")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.checkBoxSavePassword.setFont(font)
        self.checkBoxSavePassword.setAutoFillBackground(False)
        self.checkBoxSavePassword.setStyleSheet("color: rgb(235, 235, 235)")
        self.checkBoxSavePassword.setTristate(False)
        self.checkBoxSavePassword.setObjectName("checkBoxSavePassword")
        self.TitleBar = QtWidgets.QWidget(parent=self.widgetMain)
        self.TitleBar.setGeometry(QtCore.QRect(0, 0, 1500, 101))
        self.TitleBar.setStyleSheet("background-color: rgba(0,0,0,150);\n"
"")
        self.TitleBar.setObjectName("TitleBar")
        self.lineEditSearch = QtWidgets.QLineEdit(parent=self.TitleBar)
        self.lineEditSearch.setGeometry(QtCore.QRect(350, 20, 601, 61))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lineEditSearch.setFont(font)
        self.lineEditSearch.setStyleSheet("COLOR: rgb(255, 255, 255);\n"
"background-color: rgba(0,0,0,180);\n"
"\n"
"border-radius: 30px;\n"
"padding-left: 20px;\n"
"")
        self.lineEditSearch.setText("")
        self.lineEditSearch.setObjectName("lineEditSearch")
        self.pushButtonSearch = QtWidgets.QPushButton(parent=self.TitleBar)
        self.pushButtonSearch.setGeometry(QtCore.QRect(880, 30, 41, 41))
        self.pushButtonSearch.setStyleSheet("QPushButton {\n"
"    background-color: transparent;\n"
"    border-radius: 10px;\n"
"    padding: 5px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgb(71, 71, 71); \n"
"};\n"
"\n"
"")
        self.pushButtonSearch.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("C:\\Users\\OS\\LAVY\\LAVY_FINALPROJECT\\UI\\../Images/ic_search.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButtonSearch.setIcon(icon)
        self.pushButtonSearch.setIconSize(QtCore.QSize(50, 50))
        self.pushButtonSearch.setObjectName("pushButtonSearch")
        self.pushButtonWriteReview = QtWidgets.QPushButton(parent=self.TitleBar)
        self.pushButtonWriteReview.setGeometry(QtCore.QRect(960, 20, 221, 60))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonWriteReview.setFont(font)
        self.pushButtonWriteReview.setStyleSheet("QPushButton {\n"
"    background-color: transparent;\n"
"    border-radius: 10px;\n"
"    padding: 5px;\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgb(71, 71, 71); \n"
"};\n"
"\n"
"")
        self.pushButtonWriteReview.setObjectName("pushButtonWriteReview")
        self.pushButtonLogIn = QtWidgets.QPushButton(parent=self.TitleBar)
        self.pushButtonLogIn.setGeometry(QtCore.QRect(1200, 20, 140, 60))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.pushButtonLogIn.setFont(font)
        self.pushButtonLogIn.setStyleSheet("\n"
"QPushButton {\n"
"    background-color: rgb(255, 255, 255);\n"
"    border-radius: 10px;\n"
"    padding: 5px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgba(231, 230, 230, 252); \n"
"    color: black;\n"
"};\n"
"\n"
"")
        self.pushButtonLogIn.setObjectName("pushButtonLogIn")
        self.pushButtonPrevious = QtWidgets.QPushButton(parent=self.TitleBar)
        self.pushButtonPrevious.setGeometry(QtCore.QRect(20, 25, 51, 51))
        font = QtGui.QFont()
        font.setFamily("VNI-Souvir")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonPrevious.setFont(font)
        self.pushButtonPrevious.setStyleSheet("\n"
"\n"
"QPushButton {\n"
"    background-color: transparent;\n"
"    border-radius: 10px;\n"
"    padding: 5px;\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgb(71, 71, 71); \n"
"};\n"
"background-color: transparent;")
        self.pushButtonPrevious.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("C:\\Users\\OS\\LAVY\\LAVY_FINALPROJECT\\UI\\../Images/ic_left.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButtonPrevious.setIcon(icon1)
        self.pushButtonPrevious.setIconSize(QtCore.QSize(40, 40))
        self.pushButtonPrevious.setObjectName("pushButtonPrevious")
        self.pushButtonNext = QtWidgets.QPushButton(parent=self.TitleBar)
        self.pushButtonNext.setGeometry(QtCore.QRect(80, 25, 51, 51))
        font = QtGui.QFont()
        font.setFamily("VNI-Souvir")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonNext.setFont(font)
        self.pushButtonNext.setStyleSheet("\n"
"QPushButton {\n"
"    background-color: transparent;\n"
"    border-radius: 10px;\n"
"    padding: 5px;\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgb(71, 71, 71); \n"
"};\n"
"background-color: transparent;\n"
"")
        self.pushButtonNext.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("C:\\Users\\OS\\LAVY\\LAVY_FINALPROJECT\\UI\\../Images/ic_right.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButtonNext.setIcon(icon2)
        self.pushButtonNext.setIconSize(QtCore.QSize(40, 40))
        self.pushButtonNext.setObjectName("pushButtonNext")
        self.labelValy = QtWidgets.QLabel(parent=self.TitleBar)
        self.labelValy.setGeometry(QtCore.QRect(150, 0, 180, 101))
        font = QtGui.QFont()
        font.setFamily("VNI-Ariston")
        font.setPointSize(28)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.labelValy.setFont(font)
        self.labelValy.setStyleSheet("background-color: transparent;\n"
"color: rgb(255, 255, 255);\n"
"\n"
"font: 75 28pt \"VNI-Ariston\";")
        self.labelValy.setScaledContents(True)
        self.labelValy.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.labelValy.setObjectName("labelValy")
        self.pushButtonSignUp = QtWidgets.QPushButton(parent=self.TitleBar)
        self.pushButtonSignUp.setGeometry(QtCore.QRect(1350, 20, 140, 60))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.pushButtonSignUp.setFont(font)
        self.pushButtonSignUp.setStyleSheet("\n"
"QPushButton {\n"
"    background-color: rgb(255, 255, 255);\n"
"    border-radius: 10px;\n"
"    padding: 5px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgba(231, 230, 230, 252); \n"
"    color: black;\n"
"};\n"
"\n"
"")
        self.pushButtonSignUp.setObjectName("pushButtonSignUp")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.labelLogin.setText(_translate("MainWindow", "LOG IN"))
        self.lineEditUsername.setPlaceholderText(_translate("MainWindow", "Username"))
        self.lineEditPassword.setPlaceholderText(_translate("MainWindow", "Password"))
        self.pushButtonLogin.setText(_translate("MainWindow", "LOG IN"))
        self.labelForgetPassword.setText(_translate("MainWindow", "Forgot your Username or Password?"))
        self.checkBoxSavePassword.setText(_translate("MainWindow", "Save your password"))
        self.lineEditSearch.setWhatsThis(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.lineEditSearch.setPlaceholderText(_translate("MainWindow", "Search for the restaurant..."))
        self.pushButtonWriteReview.setText(_translate("MainWindow", "Write a review"))
        self.pushButtonLogIn.setText(_translate("MainWindow", "Log In"))
        self.labelValy.setText(_translate("MainWindow", "Valy"))
        self.pushButtonSignUp.setText(_translate("MainWindow", "Sign Up"))
