# Form implementation generated from reading ui file 'C:\Users\OS\LAVY\LAVY_FINALPROJECT\UI\RatingDialog.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(714, 715)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("C:\\Users\\OS\\LAVY\\LAVY_FINALPROJECT\\UI\\../Images/ic_logo.jpg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        Dialog.setWindowIcon(icon)
        self.verticalWidget = QtWidgets.QWidget(parent=Dialog)
        self.verticalWidget.setGeometry(QtCore.QRect(10, 10, 691, 681))
        self.verticalWidget.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.verticalWidget.setObjectName("verticalWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget = QtWidgets.QWidget(parent=self.verticalWidget)
        self.widget.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.widget.setObjectName("widget")
        self.label = QtWidgets.QLabel(parent=self.widget)
        self.label.setGeometry(QtCore.QRect(220, 30, 231, 221))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("C:\\Users\\OS\\LAVY\\LAVY_FINALPROJECT\\UI\\../Images/ic_starrate.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=self.widget)
        self.label_2.setGeometry(QtCore.QRect(70, 240, 531, 121))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(19)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("background-color: transparent")
        self.label_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.widget)
        self.widget_2 = QtWidgets.QWidget(parent=Dialog)
        self.widget_2.setGeometry(QtCore.QRect(10, 370, 689, 336))
        self.widget_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.widget_2.setObjectName("widget_2")
        self.pushButton_4 = QtWidgets.QPushButton(parent=self.widget_2)
        self.pushButton_4.setGeometry(QtCore.QRect(370, -20, 61, 71))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setStyleSheet("border: none\n"
"")
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(parent=self.widget_2)
        self.pushButton_5.setGeometry(QtCore.QRect(440, -20, 61, 71))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setStyleSheet("border: none\n"
"")
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_3 = QtWidgets.QPushButton(parent=self.widget_2)
        self.pushButton_3.setGeometry(QtCore.QRect(300, -20, 61, 71))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setStyleSheet("border: none\n"
"")
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_1 = QtWidgets.QPushButton(parent=self.widget_2)
        self.pushButton_1.setGeometry(QtCore.QRect(160, -20, 61, 71))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.pushButton_1.setFont(font)
        self.pushButton_1.setStyleSheet("border: none\n"
"")
        self.pushButton_1.setObjectName("pushButton_1")
        self.pushButton_2 = QtWidgets.QPushButton(parent=self.widget_2)
        self.pushButton_2.setGeometry(QtCore.QRect(230, -20, 61, 71))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("border: none\n"
"")
        self.pushButton_2.setObjectName("pushButton_2")
        self.widget_3 = QtWidgets.QWidget(parent=self.widget_2)
        self.widget_3.setGeometry(QtCore.QRect(10, 50, 671, 211))
        self.widget_3.setStyleSheet("border-color: none;\n"
"border-radius: 10px;")
        self.widget_3.setObjectName("widget_3")
        self.widget_4 = QtWidgets.QWidget(parent=self.widget_3)
        self.widget_4.setGeometry(QtCore.QRect(50, 220, 591, 61))
        self.widget_4.setObjectName("widget_4")
        self.lineEdit = QtWidgets.QLineEdit(parent=self.widget_3)
        self.lineEdit.setGeometry(QtCore.QRect(20, 30, 631, 151))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit.setFont(font)
        self.lineEdit.setAutoFillBackground(False)
        self.lineEdit.setStyleSheet("border-color: rgb(229, 229, 229);\n"
"border-radius: 10px;\n"
"font: 12pt \"Arial\";\n"
"COLOR:rgb(62, 62, 62)")
        self.lineEdit.setText("")
        self.lineEdit.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignTop)
        self.lineEdit.setCursorMoveStyle(QtCore.Qt.CursorMoveStyle.LogicalMoveStyle)
        self.lineEdit.setObjectName("lineEdit")
        self.pushButtonLogOut = QtWidgets.QPushButton(parent=self.widget_2)
        self.pushButtonLogOut.setGeometry(QtCore.QRect(190, 270, 140, 60))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(17)
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonLogOut.setFont(font)
        self.pushButtonLogOut.setStyleSheet("\n"
"QPushButton {\n"
"    background-color: rgb(255, 255, 255);\n"
"    border-radius: 10px;\n"
"    padding: 5px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgba(231, 230, 230, 252); \n"
"    color: black;\n"
"};\n"
"\n"
"")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("C:\\Users\\OS\\LAVY\\LAVY_FINALPROJECT\\UI\\../Images/ic_send.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButtonLogOut.setIcon(icon1)
        self.pushButtonLogOut.setIconSize(QtCore.QSize(20, 20))
        self.pushButtonLogOut.setObjectName("pushButtonLogOut")
        self.pushButtonLogOut_2 = QtWidgets.QPushButton(parent=self.widget_2)
        self.pushButtonLogOut_2.setGeometry(QtCore.QRect(330, 270, 140, 60))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(17)
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonLogOut_2.setFont(font)
        self.pushButtonLogOut_2.setStyleSheet("\n"
"QPushButton {\n"
"    background-color: rgb(255, 255, 255);\n"
"    border-radius: 10px;\n"
"    padding: 5px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgba(231, 230, 230, 252); \n"
"    color: black;\n"
"};\n"
"\n"
"")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("C:\\Users\\OS\\LAVY\\LAVY_FINALPROJECT\\UI\\../Images/ic_cancel.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButtonLogOut_2.setIcon(icon2)
        self.pushButtonLogOut_2.setObjectName("pushButtonLogOut_2")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Valy"))
        self.label_2.setText(_translate("Dialog", "Your opinion matter to us!"))
        self.pushButton_4.setText(_translate("Dialog", "☆"))
        self.pushButton_5.setText(_translate("Dialog", "☆"))
        self.pushButton_3.setText(_translate("Dialog", "☆"))
        self.pushButton_1.setText(_translate("Dialog", "☆"))
        self.pushButton_2.setText(_translate("Dialog", "☆"))
        self.lineEdit.setPlaceholderText(_translate("Dialog", "Write a review (Optional)"))
        self.pushButtonLogOut.setText(_translate("Dialog", "Submit"))
        self.pushButtonLogOut_2.setText(_translate("Dialog", "Cancel"))
