# Form implementation generated from reading ui file 'C:\Users\OS\LAVY\LAVY_FINALPROJECT\UI\SignUp.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(1500, 900)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.widgetMain = QtWidgets.QWidget(parent=self.centralwidget)
        self.widgetMain.setGeometry(QtCore.QRect(0, -1, 1500, 951))
        self.widgetMain.setObjectName("widgetMain")
        self.labelHomepagebackground = QtWidgets.QLabel(parent=self.widgetMain)
        self.labelHomepagebackground.setGeometry(QtCore.QRect(0, -10, 1500, 900))
        self.labelHomepagebackground.setStyleSheet("")
        self.labelHomepagebackground.setText("")
        self.labelHomepagebackground.setPixmap(QtGui.QPixmap("C:\\Users\\OS\\LAVY\\LAVY_FINALPROJECT\\UI\\../Images/backgroundlogin.jpg"))
        self.labelHomepagebackground.setScaledContents(True)
        self.labelHomepagebackground.setObjectName("labelHomepagebackground")
        self.labelBackground = QtWidgets.QLabel(parent=self.widgetMain)
        self.labelBackground.setGeometry(QtCore.QRect(0, -60, 1500, 951))
        self.labelBackground.setStyleSheet("background-color: rgba(0,0,0,150);\n"
"")
        self.labelBackground.setText("")
        self.labelBackground.setScaledContents(True)
        self.labelBackground.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.labelBackground.setObjectName("labelBackground")
        self.Main = QtWidgets.QWidget(parent=self.widgetMain)
        self.Main.setGeometry(QtCore.QRect(330, 180, 851, 631))
        self.Main.setStyleSheet("border-radius: 20px;\n"
"background-color: rgb(255, 255, 255);")
        self.Main.setObjectName("Main")
        self.labelCreateAccount = QtWidgets.QLabel(parent=self.Main)
        self.labelCreateAccount.setGeometry(QtCore.QRect(80, 50, 701, 101))
        font = QtGui.QFont()
        font.setFamily("VNI-Souvir")
        font.setPointSize(31)
        font.setStyleStrategy(QtGui.QFont.StyleStrategy.PreferAntialias)
        self.labelCreateAccount.setFont(font)
        self.labelCreateAccount.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.ArrowCursor))
        self.labelCreateAccount.setStyleSheet("COLOR:rgb(0, 0, 0)")
        self.labelCreateAccount.setScaledContents(True)
        self.labelCreateAccount.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.labelCreateAccount.setObjectName("labelCreateAccount")
        self.lineEditFirstName = QtWidgets.QLineEdit(parent=self.Main)
        self.lineEditFirstName.setGeometry(QtCore.QRect(60, 170, 321, 51))
        self.lineEditFirstName.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("VNI-Souvir")
        font.setPointSize(14)
        self.lineEditFirstName.setFont(font)
        self.lineEditFirstName.setStyleSheet("BACKGROUND-COLOR: RGBA(0,0,0,0);\n"
"BORDER: NONE;\n"
"BORDER-BOTTOM: 2PX SOLID rgb(236, 236, 236);\n"
"COLOR:rgb(0, 0, 0);\n"
"padding-bottom:7px;\n"
"padding-left: 20;")
        self.lineEditFirstName.setText("")
        self.lineEditFirstName.setObjectName("lineEditFirstName")
        self.lineEditUsername = QtWidgets.QLineEdit(parent=self.Main)
        self.lineEditUsername.setGeometry(QtCore.QRect(60, 250, 321, 51))
        self.lineEditUsername.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("VNI-Souvir")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.lineEditUsername.setFont(font)
        self.lineEditUsername.setStyleSheet("BACKGROUND-COLOR: RGBA(0,0,0,0);\n"
"BORDER: NONE;\n"
"BORDER-BOTTOM: 2PX SOLID rgb(236, 236, 236);\n"
"COLOR:rgb(0, 0, 0);\n"
"padding-bottom:7px;\n"
"padding-left: 20;")
        self.lineEditUsername.setText("")
        self.lineEditUsername.setObjectName("lineEditUsername")
        self.pushButtonSignUp1 = QtWidgets.QPushButton(parent=self.Main)
        self.pushButtonSignUp1.setGeometry(QtCore.QRect(260, 520, 321, 51))
        font = QtGui.QFont()
        font.setFamily("VNI-Souvir")
        font.setPointSize(16)
        self.pushButtonSignUp1.setFont(font)
        self.pushButtonSignUp1.setStyleSheet("\n"
"QPushButton {\n"
"    background-color: rgb(255, 255, 255);\n"
"    border-radius: 10px;\n"
"    padding: 5px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgba(231, 230, 230, 252); \n"
"    color: black;\n"
"};\n"
"")
        self.pushButtonSignUp1.setCheckable(True)
        self.pushButtonSignUp1.setAutoDefault(False)
        self.pushButtonSignUp1.setObjectName("pushButtonSignUp1")
        self.labelHaveAccount = QtWidgets.QLabel(parent=self.Main)
        self.labelHaveAccount.setGeometry(QtCore.QRect(220, 580, 401, 21))
        font = QtGui.QFont()
        font.setFamily("VNI-Souvir")
        font.setPointSize(8)
        font.setStyleStrategy(QtGui.QFont.StyleStrategy.PreferAntialias)
        self.labelHaveAccount.setFont(font)
        self.labelHaveAccount.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.ArrowCursor))
        self.labelHaveAccount.setStyleSheet("COLOR:rgb(0, 0, 0)")
        self.labelHaveAccount.setScaledContents(True)
        self.labelHaveAccount.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.labelHaveAccount.setObjectName("labelHaveAccount")
        self.lineEditLastName = QtWidgets.QLineEdit(parent=self.Main)
        self.lineEditLastName.setGeometry(QtCore.QRect(450, 170, 321, 51))
        self.lineEditLastName.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("VNI-Souvir")
        font.setPointSize(14)
        self.lineEditLastName.setFont(font)
        self.lineEditLastName.setStyleSheet("BACKGROUND-COLOR: RGBA(0,0,0,0);\n"
"BORDER: NONE;\n"
"BORDER-BOTTOM: 2PX SOLID rgb(236, 236, 236);\n"
"COLOR:rgb(0, 0, 0);\n"
"padding-bottom:7px;\n"
"padding-left: 20;")
        self.lineEditLastName.setText("")
        self.lineEditLastName.setObjectName("lineEditLastName")
        self.lineEditPassword = QtWidgets.QLineEdit(parent=self.Main)
        self.lineEditPassword.setGeometry(QtCore.QRect(450, 250, 321, 51))
        self.lineEditPassword.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("VNI-Souvir")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.lineEditPassword.setFont(font)
        self.lineEditPassword.setStyleSheet("BACKGROUND-COLOR: RGBA(0,0,0,0);\n"
"BORDER: NONE;\n"
"BORDER-BOTTOM: 2PX SOLID rgb(236, 236, 236);\n"
"COLOR:rgb(0, 0, 0);\n"
"padding-bottom:7px;\n"
"padding-left: 20;")
        self.lineEditPassword.setText("")
        self.lineEditPassword.setObjectName("lineEditPassword")
        self.lineEditEmail = QtWidgets.QLineEdit(parent=self.Main)
        self.lineEditEmail.setGeometry(QtCore.QRect(60, 330, 711, 51))
        self.lineEditEmail.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("VNI-Souvir")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.lineEditEmail.setFont(font)
        self.lineEditEmail.setStyleSheet("BACKGROUND-COLOR: RGBA(0,0,0,0);\n"
"BORDER: NONE;\n"
"BORDER-BOTTOM: 2PX SOLID rgb(236, 236, 236);\n"
"COLOR:rgb(0, 0, 0);\n"
"padding-bottom:7px;\n"
"padding-left: 20;\n"
"")
        self.lineEditEmail.setText("")
        self.lineEditEmail.setObjectName("lineEditEmail")
        self.lineEditZipCode = QtWidgets.QLineEdit(parent=self.Main)
        self.lineEditZipCode.setGeometry(QtCore.QRect(60, 410, 321, 51))
        self.lineEditZipCode.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("VNI-Souvir")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.lineEditZipCode.setFont(font)
        self.lineEditZipCode.setStyleSheet("BACKGROUND-COLOR: RGBA(0,0,0,0);\n"
"BORDER: NONE;\n"
"BORDER-BOTTOM: 2PX SOLID rgb(236, 236, 236);\n"
"COLOR:rgb(0, 0, 0);\n"
"padding-bottom:7px;\n"
"padding-left: 20;")
        self.lineEditZipCode.setText("")
        self.lineEditZipCode.setObjectName("lineEditZipCode")
        self.checkBoxRobot = QtWidgets.QCheckBox(parent=self.Main)
        self.checkBoxRobot.setGeometry(QtCore.QRect(460, 420, 191, 41))
        font = QtGui.QFont()
        font.setFamily("VNI-Souvir")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.checkBoxRobot.setFont(font)
        self.checkBoxRobot.setStyleSheet("color: rgb(0, 0, 0)")
        self.checkBoxRobot.setObjectName("checkBoxRobot")
        self.labelrecaptcha = QtWidgets.QLabel(parent=self.Main)
        self.labelrecaptcha.setGeometry(QtCore.QRect(650, 410, 71, 61))
        self.labelrecaptcha.setStyleSheet("border-image: url(:/logo/RecaptchaLogo.svg.png);")
        self.labelrecaptcha.setText("")
        self.labelrecaptcha.setObjectName("labelrecaptcha")
        self.TitleBar = QtWidgets.QWidget(parent=self.widgetMain)
        self.TitleBar.setGeometry(QtCore.QRect(0, 0, 1500, 101))
        self.TitleBar.setStyleSheet("background-color: rgba(0,0,0,150);\n"
"")
        self.TitleBar.setObjectName("TitleBar")
        self.lineEditSearch = QtWidgets.QLineEdit(parent=self.TitleBar)
        self.lineEditSearch.setGeometry(QtCore.QRect(350, 20, 601, 61))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lineEditSearch.setFont(font)
        self.lineEditSearch.setStyleSheet("COLOR: rgb(255, 255, 255);\n"
"background-color: rgba(0,0,0,180);\n"
"\n"
"border-radius: 30px;\n"
"padding-left: 20px;\n"
"")
        self.lineEditSearch.setText("")
        self.lineEditSearch.setObjectName("lineEditSearch")
        self.pushButtonSearch = QtWidgets.QPushButton(parent=self.TitleBar)
        self.pushButtonSearch.setGeometry(QtCore.QRect(880, 30, 41, 41))
        self.pushButtonSearch.setStyleSheet("QPushButton {\n"
"    background-color: transparent;\n"
"    border-radius: 10px;\n"
"    padding: 5px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgb(71, 71, 71); \n"
"};\n"
"\n"
"")
        self.pushButtonSearch.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("C:\\Users\\OS\\LAVY\\LAVY_FINALPROJECT\\UI\\../Images/ic_search.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButtonSearch.setIcon(icon)
        self.pushButtonSearch.setIconSize(QtCore.QSize(50, 50))
        self.pushButtonSearch.setObjectName("pushButtonSearch")
        self.pushButtonWriteReview = QtWidgets.QPushButton(parent=self.TitleBar)
        self.pushButtonWriteReview.setGeometry(QtCore.QRect(960, 20, 221, 60))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonWriteReview.setFont(font)
        self.pushButtonWriteReview.setStyleSheet("QPushButton {\n"
"    background-color: transparent;\n"
"    border-radius: 10px;\n"
"    padding: 5px;\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgb(71, 71, 71); \n"
"};\n"
"\n"
"")
        self.pushButtonWriteReview.setObjectName("pushButtonWriteReview")
        self.pushButtonLogIn = QtWidgets.QPushButton(parent=self.TitleBar)
        self.pushButtonLogIn.setGeometry(QtCore.QRect(1200, 20, 140, 60))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.pushButtonLogIn.setFont(font)
        self.pushButtonLogIn.setStyleSheet("\n"
"QPushButton {\n"
"    background-color: rgb(255, 255, 255);\n"
"    border-radius: 10px;\n"
"    padding: 5px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgba(231, 230, 230, 252); \n"
"    color: black;\n"
"};\n"
"\n"
"")
        self.pushButtonLogIn.setObjectName("pushButtonLogIn")
        self.pushButtonPrevious = QtWidgets.QPushButton(parent=self.TitleBar)
        self.pushButtonPrevious.setGeometry(QtCore.QRect(20, 25, 51, 51))
        font = QtGui.QFont()
        font.setFamily("VNI-Souvir")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonPrevious.setFont(font)
        self.pushButtonPrevious.setStyleSheet("\n"
"\n"
"QPushButton {\n"
"    background-color: transparent;\n"
"    border-radius: 10px;\n"
"    padding: 5px;\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgb(71, 71, 71); \n"
"};\n"
"background-color: transparent;")
        self.pushButtonPrevious.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("C:\\Users\\OS\\LAVY\\LAVY_FINALPROJECT\\UI\\../Images/ic_left.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButtonPrevious.setIcon(icon1)
        self.pushButtonPrevious.setIconSize(QtCore.QSize(40, 40))
        self.pushButtonPrevious.setObjectName("pushButtonPrevious")
        self.pushButtonNext = QtWidgets.QPushButton(parent=self.TitleBar)
        self.pushButtonNext.setGeometry(QtCore.QRect(80, 25, 51, 51))
        font = QtGui.QFont()
        font.setFamily("VNI-Souvir")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonNext.setFont(font)
        self.pushButtonNext.setStyleSheet("\n"
"QPushButton {\n"
"    background-color: transparent;\n"
"    border-radius: 10px;\n"
"    padding: 5px;\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgb(71, 71, 71); \n"
"};\n"
"background-color: transparent;\n"
"")
        self.pushButtonNext.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("C:\\Users\\OS\\LAVY\\LAVY_FINALPROJECT\\UI\\../Images/ic_right.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButtonNext.setIcon(icon2)
        self.pushButtonNext.setIconSize(QtCore.QSize(40, 40))
        self.pushButtonNext.setObjectName("pushButtonNext")
        self.labelValy = QtWidgets.QLabel(parent=self.TitleBar)
        self.labelValy.setGeometry(QtCore.QRect(150, 0, 180, 101))
        font = QtGui.QFont()
        font.setFamily("VNI-Ariston")
        font.setPointSize(28)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.labelValy.setFont(font)
        self.labelValy.setStyleSheet("background-color: transparent;\n"
"color: rgb(255, 255, 255);\n"
"\n"
"font: 75 28pt \"VNI-Ariston\";")
        self.labelValy.setScaledContents(True)
        self.labelValy.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.labelValy.setObjectName("labelValy")
        self.pushButtonSignUp = QtWidgets.QPushButton(parent=self.TitleBar)
        self.pushButtonSignUp.setGeometry(QtCore.QRect(1350, 20, 140, 60))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.pushButtonSignUp.setFont(font)
        self.pushButtonSignUp.setStyleSheet("\n"
"QPushButton {\n"
"    background-color: rgb(255, 255, 255);\n"
"    border-radius: 10px;\n"
"    padding: 5px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgba(231, 230, 230, 252); \n"
"    color: black;\n"
"};\n"
"\n"
"")
        self.pushButtonSignUp.setObjectName("pushButtonSignUp")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.labelCreateAccount.setText(_translate("MainWindow", "CREATE AN ACCOUNT"))
        self.lineEditFirstName.setPlaceholderText(_translate("MainWindow", "First Name"))
        self.lineEditUsername.setPlaceholderText(_translate("MainWindow", "Username"))
        self.pushButtonSignUp1.setText(_translate("MainWindow", "SIGN UP"))
        self.labelHaveAccount.setText(_translate("MainWindow", "Have an account?"))
        self.lineEditLastName.setPlaceholderText(_translate("MainWindow", "Last Name"))
        self.lineEditPassword.setPlaceholderText(_translate("MainWindow", "Password"))
        self.lineEditEmail.setPlaceholderText(_translate("MainWindow", "Email"))
        self.lineEditZipCode.setPlaceholderText(_translate("MainWindow", "Zip Code"))
        self.checkBoxRobot.setText(_translate("MainWindow", "I\'m not a robot"))
        self.lineEditSearch.setWhatsThis(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.lineEditSearch.setPlaceholderText(_translate("MainWindow", "Search for the restaurant..."))
        self.pushButtonWriteReview.setText(_translate("MainWindow", "Write a review"))
        self.pushButtonLogIn.setText(_translate("MainWindow", "Log In"))
        self.labelValy.setText(_translate("MainWindow", "Valy"))
        self.pushButtonSignUp.setText(_translate("MainWindow", "Sign Up"))
